-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.2
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:ADCR

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

SET check_function_bodies = false;

CREATE SCHEMA IF NOT EXISTS doma_pandameta;
ALTER SCHEMA doma_pandameta OWNER TO panda;

SET search_path = doma_pandameta,public;

CREATE TABLE agis_dump (
	panda_site varchar(52),
	update_time timestamp,
	json_data text
) ;
ALTER TABLE agis_dump OWNER TO panda;

CREATE TABLE auth_group (
	id bigint,
	name varchar(80)
) ;
ALTER TABLE auth_group OWNER TO panda;

CREATE TABLE auth_group_permissions (
	id bigint,
	group_id bigint,
	permission_id bigint
) ;
ALTER TABLE auth_group_permissions OWNER TO panda;

CREATE TABLE auth_user_groups (
	id bigint,
	user_id bigint,
	group_id bigint
) ;
ALTER TABLE auth_user_groups OWNER TO panda;

CREATE TABLE auth_user_user_permissions (
	id bigint,
	user_id bigint,
	permission_id bigint
) ;
ALTER TABLE auth_user_user_permissions OWNER TO panda;

CREATE TABLE cloudconfig (
	name varchar(20) NOT NULL,
	description varchar(50) NOT NULL,
	tier1 varchar(20) NOT NULL,
	tier1se varchar(400) NOT NULL,
	relocation varchar(10),
	weight bigint NOT NULL DEFAULT '0',
	server varchar(100) NOT NULL,
	status varchar(20) NOT NULL,
	transtimelo bigint NOT NULL DEFAULT '0',
	transtimehi bigint NOT NULL DEFAULT '0',
	waittime bigint NOT NULL DEFAULT '0',
	comment_ varchar(200),
	space bigint NOT NULL DEFAULT '0',
	moduser varchar(30),
	modtime timestamp NOT NULL DEFAULT LOCALTIMESTAMP,
	validation varchar(20),
	mcshare bigint NOT NULL DEFAULT '0',
	countries varchar(80),
	fasttrack varchar(20),
	nprestage bigint NOT NULL DEFAULT 0,
	pilotowners varchar(300),
	dn varchar(100),
	email varchar(60),
	fairshare varchar(256),
	auto_mcu smallint DEFAULT 0
) ;
COMMENT ON COLUMN cloudconfig.comment_ IS E'ORIGINAL NAME:comment';
ALTER  TABLE cloudconfig OWNER TO panda;
ALTER TABLE cloudconfig ADD PRIMARY KEY (name);
ALTER TABLE cloudconfig ADD CONSTRAINT cloudconfig_auto_mcu_check CHECK (auto_mcu IN (0,1));
ALTER TABLE cloudconfig ALTER COLUMN auto_mcu SET NOT NULL;
ALTER TABLE cloudconfig ALTER COLUMN NAME SET NOT NULL;
ALTER TABLE cloudconfig ALTER COLUMN DESCRIPTION SET NOT NULL;
ALTER TABLE cloudconfig ALTER COLUMN TIER1 SET NOT NULL;
ALTER TABLE cloudconfig ALTER COLUMN TIER1SE SET NOT NULL;
ALTER TABLE cloudconfig ALTER COLUMN WEIGHT SET NOT NULL;
ALTER TABLE cloudconfig ALTER COLUMN SERVER SET NOT NULL;
ALTER TABLE cloudconfig ALTER COLUMN STATUS SET NOT NULL;
ALTER TABLE cloudconfig ALTER COLUMN TRANSTIMELO SET NOT NULL;
ALTER TABLE cloudconfig ALTER COLUMN TRANSTIMEHI SET NOT NULL;
ALTER TABLE cloudconfig ALTER COLUMN WAITTIME SET NOT NULL;
ALTER TABLE cloudconfig ALTER COLUMN SPACE SET NOT NULL;
ALTER TABLE cloudconfig ALTER COLUMN MODTIME SET NOT NULL;
ALTER TABLE cloudconfig ALTER COLUMN MCSHARE SET NOT NULL;
ALTER TABLE cloudconfig ALTER COLUMN NPRESTAGE SET NOT NULL;


CREATE TABLE incidents (
	at_time timestamp,
	typekey varchar(20),
	description varchar(200)
) ;
ALTER  TABLE incidents OWNER TO panda;


CREATE TABLE jdllist (
	name varchar(60) NOT NULL,
	host varchar(60),
	system varchar(20) NOT NULL,
	jdl varchar(4000)
) ;
ALTER  TABLE jdllist OWNER TO panda;
ALTER TABLE jdllist ADD PRIMARY KEY (name);
ALTER TABLE jdllist ALTER COLUMN NAME SET NOT NULL;
ALTER TABLE jdllist ALTER COLUMN SYSTEM SET NOT NULL;


CREATE TABLE jobclass (
	id integer NOT NULL,
	name varchar(30) NOT NULL,
	description varchar(30) NOT NULL,
	rights varchar(30),
	priority integer,
	quota1 bigint,
	quota7 bigint,
	quota30 bigint
) ;
ALTER  TABLE jobclass OWNER TO panda;
CREATE UNIQUE INDEX jobclass_name_idx ON jobclass (name);
ALTER TABLE jobclass ADD PRIMARY KEY (id);
ALTER TABLE jobclass ALTER COLUMN ID SET NOT NULL;
ALTER TABLE jobclass ALTER COLUMN NAME SET NOT NULL;
ALTER TABLE jobclass ALTER COLUMN DESCRIPTION SET NOT NULL;


CREATE TABLE logstable (
	pandaid bigint NOT NULL DEFAULT '0',
	log1 text NOT NULL,
	log2 text NOT NULL,
	log3 text NOT NULL,
	log4 text NOT NULL
) ;
ALTER  TABLE logstable OWNER TO panda;
ALTER TABLE logstable ADD PRIMARY KEY (pandaid);
ALTER TABLE logstable ALTER COLUMN LOG4 SET NOT NULL;
ALTER TABLE logstable ALTER COLUMN LOG3 SET NOT NULL;
ALTER TABLE logstable ALTER COLUMN LOG2 SET NOT NULL;
ALTER TABLE logstable ALTER COLUMN LOG1 SET NOT NULL;
ALTER TABLE logstable ALTER COLUMN PANDAID SET NOT NULL;


CREATE TABLE multicloud_history (
	site varchar(60) NOT NULL,
	multicloud varchar(64),
	last_update timestamp NOT NULL
) ;
ALTER  TABLE multicloud_history OWNER TO panda;
CREATE INDEX multicloud_history_site_idx ON multicloud_history (site);
ALTER TABLE multicloud_history ALTER COLUMN LAST_UPDATE SET NOT NULL;
ALTER TABLE multicloud_history ALTER COLUMN SITE SET NOT NULL;


CREATE TABLE pandaconfig (
	name varchar(60) NOT NULL,
	controller varchar(20) NOT NULL,
	pathena varchar(20)
) ;
ALTER  TABLE pandaconfig OWNER TO panda;
ALTER TABLE pandaconfig ADD PRIMARY KEY (name);
ALTER TABLE pandaconfig ALTER COLUMN NAME SET NOT NULL;
ALTER TABLE pandaconfig ALTER COLUMN CONTROLLER SET NOT NULL;


CREATE TABLE proxykey (
	id bigint NOT NULL,
	dn varchar(100) NOT NULL,
	credname varchar(40) NOT NULL,
	created timestamp NOT NULL DEFAULT LOCALTIMESTAMP,
	expires timestamp NOT NULL DEFAULT to_date('01-JAN-70 00:00:00','dd-MON-yy hh24:mi:ss'),
	origin varchar(80) NOT NULL,
	myproxy varchar(80) NOT NULL
) ;
ALTER  TABLE proxykey OWNER TO panda;
ALTER TABLE proxykey ADD PRIMARY KEY (id);
ALTER TABLE proxykey ALTER COLUMN ID SET NOT NULL;
ALTER TABLE proxykey ALTER COLUMN DN SET NOT NULL;
ALTER TABLE proxykey ALTER COLUMN CREDNAME SET NOT NULL;
ALTER TABLE proxykey ALTER COLUMN CREATED SET NOT NULL;
ALTER TABLE proxykey ALTER COLUMN EXPIRES SET NOT NULL;
ALTER TABLE proxykey ALTER COLUMN ORIGIN SET NOT NULL;
ALTER TABLE proxykey ALTER COLUMN MYPROXY SET NOT NULL;


CREATE TABLE schedinstance (
	name varchar(60) NOT NULL DEFAULT 'default',
	nickname varchar(60) NOT NULL,
	pandasite varchar(60) NOT NULL,
	nqueue bigint NOT NULL DEFAULT '5',
	nqueued bigint NOT NULL DEFAULT '0',
	nrunning bigint NOT NULL DEFAULT '0',
	nfinished bigint NOT NULL DEFAULT '0',
	nfailed bigint NOT NULL DEFAULT '0',
	naborted bigint NOT NULL DEFAULT '0',
	njobs bigint NOT NULL DEFAULT '0',
	tvalid timestamp NOT NULL DEFAULT LOCALTIMESTAMP,
	lastmod timestamp NOT NULL DEFAULT to_date('01-JAN-70 00:00:00','dd-MON-yy hh24:mi:ss'),
	errinfo varchar(150),
	ndone bigint NOT NULL DEFAULT '0',
	totrunt bigint NOT NULL DEFAULT '0',
	comment_ varchar(500)
) ;
COMMENT ON COLUMN schedinstance.comment_ IS E'ORIGINAL NAME:comment';
ALTER  TABLE schedinstance OWNER TO panda;
CREATE INDEX schedinstance_nickname_idx ON schedinstance (nickname);
ALTER TABLE schedinstance ADD PRIMARY KEY (nickname,pandasite);
ALTER TABLE schedinstance ALTER COLUMN NAME SET NOT NULL;
ALTER TABLE schedinstance ALTER COLUMN NICKNAME SET NOT NULL;
ALTER TABLE schedinstance ALTER COLUMN NQUEUE SET NOT NULL;
ALTER TABLE schedinstance ALTER COLUMN NQUEUED SET NOT NULL;
ALTER TABLE schedinstance ALTER COLUMN NRUNNING SET NOT NULL;
ALTER TABLE schedinstance ALTER COLUMN NFINISHED SET NOT NULL;
ALTER TABLE schedinstance ALTER COLUMN NFAILED SET NOT NULL;
ALTER TABLE schedinstance ALTER COLUMN NABORTED SET NOT NULL;
ALTER TABLE schedinstance ALTER COLUMN NJOBS SET NOT NULL;
ALTER TABLE schedinstance ALTER COLUMN TVALID SET NOT NULL;
ALTER TABLE schedinstance ALTER COLUMN LASTMOD SET NOT NULL;
ALTER TABLE schedinstance ALTER COLUMN NDONE SET NOT NULL;
ALTER TABLE schedinstance ALTER COLUMN TOTRUNT SET NOT NULL;


CREATE TABLE siteaccess (
	id bigint NOT NULL,
	dn varchar(100),
	pandasite varchar(100),
	poffset bigint NOT NULL DEFAULT 0,
	rights varchar(30),
	status varchar(20),
	workinggroups varchar(100),
	created timestamp
) ;
ALTER  TABLE siteaccess OWNER TO panda;
CREATE UNIQUE INDEX siteaccess_dnsite_idx ON siteaccess (dn, pandasite);
ALTER TABLE siteaccess ADD PRIMARY KEY (id);
ALTER TABLE siteaccess ALTER COLUMN ID SET NOT NULL;
ALTER TABLE siteaccess ALTER COLUMN POFFSET SET NOT NULL;


CREATE TABLE sitedata (
	site varchar(60) NOT NULL,
	flag varchar(30) NOT NULL,
	hours integer NOT NULL DEFAULT '0',
	nwn integer,
	memmin integer,
	memmax integer,
	si2000min integer,
	si2000max integer,
	os varchar(30),
	space varchar(30),
	minjobs integer,
	maxjobs integer,
	laststart timestamp,
	lastend timestamp,
	lastfail timestamp,
	lastpilot timestamp,
	lastpid integer,
	nstart integer NOT NULL DEFAULT '0',
	finished integer NOT NULL DEFAULT '0',
	failed integer NOT NULL DEFAULT '0',
	defined integer NOT NULL DEFAULT '0',
	assigned integer NOT NULL DEFAULT '0',
	waiting integer NOT NULL DEFAULT '0',
	activated integer NOT NULL DEFAULT '0',
	holding integer NOT NULL DEFAULT '0',
	running integer NOT NULL DEFAULT '0',
	transferring integer NOT NULL DEFAULT '0',
	getjob integer NOT NULL DEFAULT '0',
	updatejob integer NOT NULL DEFAULT '0',
	lastmod timestamp NOT NULL DEFAULT LOCALTIMESTAMP,
	ncpu integer,
	nslot integer,
	nojob integer,
	getjobabs bigint,
	updatejobabs bigint,
	nojobabs bigint
) ;
COMMENT ON COLUMN sitedata.getjobabs IS E'Absolute number of getJobs requests';
COMMENT ON COLUMN sitedata.nojob IS E'Number of getJobs requests that did not get a Job';
COMMENT ON COLUMN sitedata.nojobabs IS E'Absolute number of getJobs requests that did not get a Job';
COMMENT ON COLUMN sitedata.updatejobabs IS E'Absolute number of updateJobs';
ALTER  TABLE sitedata OWNER TO panda;
ALTER TABLE sitedata ADD PRIMARY KEY (site,flag,hours);
ALTER TABLE sitedata ALTER COLUMN SITE SET NOT NULL;
ALTER TABLE sitedata ALTER COLUMN FLAG SET NOT NULL;
ALTER TABLE sitedata ALTER COLUMN HOURS SET NOT NULL;
ALTER TABLE sitedata ALTER COLUMN NSTART SET NOT NULL;
ALTER TABLE sitedata ALTER COLUMN FINISHED SET NOT NULL;
ALTER TABLE sitedata ALTER COLUMN FAILED SET NOT NULL;
ALTER TABLE sitedata ALTER COLUMN DEFINED SET NOT NULL;
ALTER TABLE sitedata ALTER COLUMN ASSIGNED SET NOT NULL;
ALTER TABLE sitedata ALTER COLUMN WAITING SET NOT NULL;
ALTER TABLE sitedata ALTER COLUMN ACTIVATED SET NOT NULL;
ALTER TABLE sitedata ALTER COLUMN HOLDING SET NOT NULL;
ALTER TABLE sitedata ALTER COLUMN RUNNING SET NOT NULL;
ALTER TABLE sitedata ALTER COLUMN TRANSFERRING SET NOT NULL;
ALTER TABLE sitedata ALTER COLUMN GETJOB SET NOT NULL;
ALTER TABLE sitedata ALTER COLUMN UPDATEJOB SET NOT NULL;
ALTER TABLE sitedata ALTER COLUMN LASTMOD SET NOT NULL;


CREATE TABLE sites_matrix_data (
	source varchar(256) NOT NULL,
	destination varchar(256) NOT NULL,
	meas_date timestamp NOT NULL,
	sonarsmlval bigint,
	sonarsmldev bigint,
	sonarmedval bigint,
	sonarmeddev bigint,
	sonarlrgval bigint,
	sonarlrgdev bigint,
	perfsonaravgval bigint,
	xrdcpval bigint,
	sonarsml_last_update timestamp,
	sonarmed_last_update timestamp,
	sonarlrg_last_update timestamp,
	perfsonaravg_last_update timestamp,
	xrdcp_last_update timestamp
) ;
ALTER  TABLE sites_matrix_data OWNER TO panda;
ALTER TABLE sites_matrix_data ADD PRIMARY KEY (source,destination);
ALTER TABLE sites_matrix_data ALTER COLUMN MEAS_DATE SET NOT NULL;
ALTER TABLE sites_matrix_data ALTER COLUMN DESTINATION SET NOT NULL;
ALTER TABLE sites_matrix_data ALTER COLUMN SOURCE SET NOT NULL;


CREATE TABLE taginfo (
	tag varchar(30) NOT NULL,
	description varchar(100) NOT NULL,
	nqueues bigint NOT NULL DEFAULT '0',
	queues varchar(4000)
) ;
ALTER  TABLE taginfo OWNER TO panda;
ALTER TABLE taginfo ADD PRIMARY KEY (tag);
ALTER TABLE taginfo ALTER COLUMN DESCRIPTION SET NOT NULL;
ALTER TABLE taginfo ALTER COLUMN NQUEUES SET NOT NULL;


CREATE TABLE usercacheusage (
	username varchar(128) NOT NULL,
	filename varchar(256) NOT NULL,
	hostname varchar(64) NOT NULL,
	creationtime timestamp NOT NULL,
	modificationtime timestamp,
	filesize bigint,
	checksum varchar(36),
	aliasname varchar(256)
) PARTITION BY RANGE (creationtime) ;
COMMENT ON TABLE usercacheusage IS E'This table is required to keep track on the disk usage per user, so that can be seen who unfairly occupies too much disk space and eventually ban the user';
ALTER  TABLE usercacheusage OWNER TO panda;
CREATE INDEX usercacheusage_usr_crdate_indx ON usercacheusage (username, creationtime);
ALTER TABLE usercacheusage ADD PRIMARY KEY (filename,hostname,creationtime);
ALTER TABLE usercacheusage ALTER COLUMN USERNAME SET NOT NULL;
ALTER TABLE usercacheusage ALTER COLUMN FILENAME SET NOT NULL;
ALTER TABLE usercacheusage ALTER COLUMN HOSTNAME SET NOT NULL;
ALTER TABLE usercacheusage ALTER COLUMN CREATIONTIME SET NOT NULL;


CREATE TABLE users (
	id integer NOT NULL,
	name varchar(60) NOT NULL,
	dn varchar(150),
	email varchar(60),
	url varchar(100),
	location varchar(60),
	classa varchar(30),
	classp varchar(30),
	classxp varchar(30),
	sitepref varchar(60),
	gridpref varchar(20),
	queuepref varchar(60),
	scriptcache varchar(100),
	types varchar(60),
	sites varchar(250),
	njobsa bigint,
	njobsp bigint,
	njobs1 bigint,
	njobs7 bigint,
	njobs30 bigint,
	cpua1 bigint,
	cpua7 bigint,
	cpua30 bigint,
	cpup1 bigint,
	cpup7 bigint,
	cpup30 bigint,
	cpuxp1 bigint,
	cpuxp7 bigint,
	cpuxp30 bigint,
	quotaa1 bigint,
	quotaa7 bigint,
	quotaa30 bigint,
	quotap1 bigint,
	quotap7 bigint,
	quotap30 bigint,
	quotaxp1 bigint,
	quotaxp7 bigint,
	quotaxp30 bigint,
	space1 bigint,
	space7 bigint,
	space30 bigint,
	lastmod timestamp NOT NULL DEFAULT LOCALTIMESTAMP,
	firstjob timestamp NOT NULL DEFAULT to_date('01-JAN-70 00:00:00','dd-MON-yy hh24:mi:ss'),
	latestjob timestamp NOT NULL DEFAULT to_date('01-JAN-70 00:00:00','dd-MON-yy hh24:mi:ss'),
	pagecache text,
	cachetime timestamp NOT NULL DEFAULT to_date('01-JAN-70 00:00:00','dd-MON-yy hh24:mi:ss'),
	ncurrent bigint NOT NULL DEFAULT '0',
	jobid bigint NOT NULL DEFAULT '0',
	status varchar(20),
	vo varchar(20)
) ;
ALTER  TABLE users OWNER TO panda;
CREATE INDEX users_name_idx ON users (name, vo);
ALTER TABLE users ADD PRIMARY KEY (id);
ALTER TABLE users ALTER COLUMN ID SET NOT NULL;
ALTER TABLE users ALTER COLUMN NAME SET NOT NULL;
ALTER TABLE users ALTER COLUMN LASTMOD SET NOT NULL;
ALTER TABLE users ALTER COLUMN FIRSTJOB SET NOT NULL;
ALTER TABLE users ALTER COLUMN LATESTJOB SET NOT NULL;
ALTER TABLE users ALTER COLUMN CACHETIME SET NOT NULL;
ALTER TABLE users ALTER COLUMN NCURRENT SET NOT NULL;
ALTER TABLE users ALTER COLUMN JOBID SET NOT NULL;


CREATE TABLE usersubs (
	datasetname varchar(255) NOT NULL,
	site varchar(64) NOT NULL,
	creationdate timestamp,
	modificationdate timestamp,
	nused integer,
	state varchar(30) DEFAULT 'subscribed'
) ;
ALTER  TABLE usersubs OWNER TO panda;
ALTER TABLE usersubs ADD PRIMARY KEY (datasetname,site);
ALTER TABLE usersubs ALTER COLUMN DATASETNAME SET NOT NULL;
ALTER TABLE usersubs ALTER COLUMN SITE SET NOT NULL;
