-- Generated by Ora2Pg, the Oracle database Schema converter, version 21.1
-- Copyright 2000-2020 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:INT8R

SET client_encoding TO 'UTF8';

SET search_path = doma_pandabigmon,public;
\set ON_ERROR_STOP ON

SET check_function_bodies = false;



CREATE OR REPLACE PROCEDURE doma_pandabigmon.do_grants (obj_type text, obj_name text,owner_name text) AS $body$
DECLARE

	
	
	privs varchar(100);
BEGIN

	 -- need to put " " around the object names, because some users create the objects with preserved character case.
	IF (obj_name NOT IN ('DO_GRANTS','GRANTS_UPDATE','CREATE_SYN4EXIST_OBJ') AND substr(obj_name,1,4)<>'BIN$' AND substr(obj_name,1,4)<>'SYS_' ) THEN

		IF obj_type IN ('TABLE') THEN
        	 	EXECUTE 'GRANT SELECT,INSERT,UPDATE,DELETE on "'||obj_name||'" to doma_pandabigmon_w';
		        EXECUTE 'GRANT SELECT on "'||obj_name||'" to doma_pandabigmon_r';
		elsif obj_type = 'SEQUENCE' THEN
	        	EXECUTE 'GRANT SELECT on "'||obj_name||'" to doma_pandabigmon_w';
		        EXECUTE 'GRANT SELECT on "'||obj_name||'" to doma_pandabigmon_r';
		elsif obj_type IN ('VIEW', 'MATERIALIZED VIEW') THEN
			privs := ' SELECT,INSERT,UPDATE,DELETE ';
			FOR i IN 1..2 LOOP /*if fails on the first loop with error 01720, then goes to the EXEPTION and changes the statement */
				BEGIN
					EXECUTE 'GRANT '|| privs ||' on "'|| obj_name||'" to doma_pandabigmon_w';
				        EXECUTE 'GRANT SELECT on "'||obj_name||'" to doma_pandabigmon_r';
					EXIT;
				EXCEPTION
					WHEN SQLSTATE '50001' THEN
						privs := ' SELECT ';
				END;
			END LOOP;
		elsif obj_type IN ('PROCEDURE', 'PACKAGE','FUNCTION', 'TYPE') AND obj_name <> 'CREATE_SYN' THEN
	         	EXECUTE 'GRANT EXECUTE on "'||obj_name||'" to doma_pandabigmon_w';
		        EXECUTE 'GRANT EXECUTE on "'||obj_name||'" to doma_pandabigmon_r';
		END IF;
	END IF;
END;
$body$
LANGUAGE PLPGSQL
;
ALTER PROCEDURE do_grants (obj_type text, obj_name text,owner_name text) OWNER TO panda;
-- REVOKE ALL ON PROCEDURE doma_pandabigmon.do_grants (obj_type text, obj_name text,owner_name text) FROM PUBLIC;



CREATE OR REPLACE PROCEDURE doma_pandabigmon.grant_privs4exist_obj (owner_name text ) AS $body$
DECLARE

	
	
	privs varchar(100);
  rec RECORD;
BEGIN
 -- need to put " " around the object names, because some users create the objects with preserved character case.
	-- IMPORTANT - GRANT OBJECT PRIVILEGES FIRST TO THE TABLES
	FOR rec in (SELECT object_name as obj_name, object_type as obj_type FROM all_objects WHERE owner = 'doma_pandabigmon' and object_type = 'table' and substr(object_name,1,4)<>'bin$' and substr(object_name,1,4)<>'sys_') loop
       	 	EXECUTE 'GRANT SELECT,INSERT,UPDATE,DELETE on "'||rec.obj_name||'" to doma_pandabigmon_w';
	        EXECUTE 'GRANT SELECT on "'||rec.obj_name||'" to doma_pandabigmon_r';
	END LOOP;

	FOR rec in (SELECT object_name as obj_name, object_type as obj_type FROM all_objects WHERE owner = 'doma_pandabigmon' and object_type in ('view','sequence','procedure', 'package', 'function', 'materialized view', 'type' ) order by object_type desc ) loop

		IF rec.obj_name NOT IN ('DO_GRANTS','GRANTS_UPDATE','GRANT_PRIVS4EXIST_OBJ') THEN
			IF rec.obj_type IN ('VIEW', 'MATERIALIZED VIEW' ) THEN
				privs := ' SELECT,INSERT,UPDATE,DELETE ';
				FOR i IN 1..2 LOOP /*if fails on the first loop with error 01720, then goes to the EXEPTION and changes the statement */
					BEGIN
						EXECUTE 'GRANT '|| privs ||' on "'||rec.obj_name||'" to doma_pandabigmon_w';
					        EXECUTE 'GRANT SELECT on "'||rec.obj_name||'" to doma_pandabigmon_r';
						EXIT;
					EXCEPTION
						WHEN SQLSTATE '50001' THEN
						privs := ' SELECT ';
					END;
				END LOOP;
			elsif rec.obj_type = 'SEQUENCE' THEN
	        		EXECUTE 'GRANT SELECT on "'||rec.obj_name||'" to doma_pandabigmon_w';
			        EXECUTE 'GRANT SELECT on "'||rec.obj_name||'" to doma_pandabigmon_r';
			elsif rec.obj_type IN ('PROCEDURE', 'PACKAGE','FUNCTION', 'TYPE') AND rec.obj_name <> 'CREATE_SYN' THEN
		         	EXECUTE 'GRANT EXECUTE on "'||rec.obj_name||'" to doma_pandabigmon_w';
			        EXECUTE 'GRANT EXECUTE on "'||rec.obj_name||'" to doma_pandabigmon_r';
			END IF;
		END IF;
	END LOOP;
END;
$body$
LANGUAGE PLPGSQL
;
ALTER PROCEDURE grant_privs4exist_obj (owner_name text ) OWNER TO panda;
-- REVOKE ALL ON PROCEDURE doma_pandabigmon.grant_privs4exist_obj (owner_name text ) FROM PUBLIC;
