-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.2
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:ADCR

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

SET check_function_bodies = false;

CREATE SCHEMA IF NOT EXISTS doma_pandaarch;
ALTER SCHEMA doma_pandaarch OWNER TO panda;

SET search_path = doma_pandaarch,public;


CREATE TABLE filestable_arch (
	row_id bigint NOT NULL,
	pandaid bigint NOT NULL DEFAULT 0,
	modificationtime timestamp NOT NULL DEFAULT LOCALTIMESTAMP,
	creationtime timestamp,
	guid varchar(64),
	lfn varchar(256),
	type varchar(20),
	fsize bigint DEFAULT 0,
	dataset varchar(255),
	status varchar(64),
	md5sum varchar(40),
	checksum varchar(40),
	proddblock varchar(255),
	proddblocktoken varchar(250),
	dispatchdblock varchar(255),
	dispatchdblocktoken varchar(250),
	destinationdblock varchar(255),
	destinationdblocktoken varchar(250),
	destinationse varchar(250),
	scope varchar(30),
	jeditaskid bigint,
	datasetid bigint,
	fileid bigint,
	attemptnr smallint
) ;
ALTER  TABLE filestable_arch OWNER TO panda;
CREATE INDEX files_arch_lfn_idx ON filestable_arch (lfn);
CREATE INDEX files_arch_pandaid_idx ON filestable_arch (pandaid);
CREATE INDEX files_arch_rowid_idx ON filestable_arch (row_id);
CREATE INDEX file_arch_task_dset_fileid_idx ON filestable_arch (jeditaskid, datasetid, fileid, pandaid);
ALTER TABLE filestable_arch ALTER COLUMN ROW_ID SET NOT NULL;
ALTER TABLE filestable_arch ALTER COLUMN PANDAID SET NOT NULL;
ALTER TABLE filestable_arch ALTER COLUMN MODIFICATIONTIME SET NOT NULL;


CREATE TABLE jobparamstable_arch (
	pandaid bigint NOT NULL,
	modificationtime timestamp NOT NULL DEFAULT LOCALTIMESTAMP,
	jobparameters text
) ;
ALTER  TABLE jobparamstable_arch OWNER TO panda;
CREATE INDEX jobparams_arch_pandaid_idx ON jobparamstable_arch (pandaid);
ALTER TABLE jobparamstable_arch ALTER COLUMN PANDAID SET NOT NULL;
ALTER TABLE jobparamstable_arch ALTER COLUMN MODIFICATIONTIME SET NOT NULL;


CREATE TABLE jobsarchived (
	pandaid bigint NOT NULL DEFAULT '0',
	jobdefinitionid bigint NOT NULL DEFAULT '0',
	schedulerid varchar(128),
	pilotid varchar(200),
	creationtime timestamp NOT NULL DEFAULT LOCALTIMESTAMP,
	creationhost varchar(128),
	modificationtime timestamp NOT NULL DEFAULT LOCALTIMESTAMP,
	modificationhost varchar(128),
	atlasrelease varchar(64),
	transformation varchar(250),
	homepackage varchar(80),
	prodserieslabel varchar(20),
	prodsourcelabel varchar(20),
	produserid varchar(250),
	assignedpriority integer NOT NULL DEFAULT '0',
	currentpriority integer NOT NULL DEFAULT '0',
	attemptnr smallint NOT NULL DEFAULT '0',
	maxattempt smallint NOT NULL DEFAULT '0',
	jobstatus varchar(15) NOT NULL DEFAULT 'unknown',
	jobname varchar(256),
	maxcpucount bigint NOT NULL DEFAULT '0',
	maxcpuunit varchar(32),
	maxdiskcount bigint NOT NULL DEFAULT '0',
	maxdiskunit char(4),
	ipconnectivity char(5),
	minramcount bigint NOT NULL DEFAULT '0',
	minramunit char(4),
	starttime timestamp DEFAULT LOCALTIMESTAMP,
	endtime timestamp DEFAULT LOCALTIMESTAMP,
	cpuconsumptiontime numeric(20),
	cpuconsumptionunit varchar(128),
	commandtopilot varchar(250),
	transexitcode varchar(128),
	piloterrorcode integer NOT NULL DEFAULT '0',
	piloterrordiag varchar(500),
	exeerrorcode integer NOT NULL DEFAULT '0',
	exeerrordiag varchar(500),
	superrorcode integer NOT NULL DEFAULT '0',
	superrordiag varchar(250),
	ddmerrorcode integer NOT NULL DEFAULT '0',
	ddmerrordiag varchar(700),
	brokerageerrorcode integer NOT NULL DEFAULT '0',
	brokerageerrordiag varchar(250),
	jobdispatchererrorcode integer NOT NULL DEFAULT '0',
	jobdispatchererrordiag varchar(250),
	taskbuffererrorcode integer NOT NULL DEFAULT '0',
	taskbuffererrordiag varchar(300),
	computingsite varchar(128),
	computingelement varchar(128),
	proddblock varchar(255),
	dispatchdblock varchar(255),
	destinationdblock varchar(255),
	destinationse varchar(250),
	nevents bigint,
	grid varchar(50),
	cloud varchar(50),
	cpuconversion decimal(9,4),
	sourcesite varchar(36),
	destinationsite varchar(36),
	transfertype varchar(10),
	taskid integer,
	cmtconfig varchar(250),
	statechangetime timestamp DEFAULT LOCALTIMESTAMP,
	proddbupdatetime timestamp DEFAULT LOCALTIMESTAMP,
	lockedby varchar(128),
	relocationflag smallint DEFAULT '0',
	jobexecutionid bigint DEFAULT '0',
	vo varchar(16),
	pilottiming varchar(100),
	workinggroup varchar(20),
	processingtype varchar(64),
	jobparameters text,
	metadata text,
	produsername varchar(60),
	ninputfiles integer,
	countrygroup varchar(20),
	batchid varchar(80),
	parentid bigint,
	specialhandling varchar(80),
	jobsetid bigint,
	corecount smallint,
	ninputdatafiles integer,
	inputfiletype varchar(32),
	inputfileproject varchar(64),
	inputfilebytes bigint,
	noutputdatafiles integer,
	outputfilebytes bigint,
	jobmetrics varchar(500),
	workqueue_id integer,
	jeditaskid bigint,
	jobsubstatus varchar(80),
	actualcorecount integer,
	reqid integer,
	maxrss bigint,
	maxvmem bigint,
	maxswap bigint,
	maxpss bigint,
	avgrss bigint,
	avgvmem bigint,
	avgswap bigint,
	avgpss bigint,
	maxwalltime bigint,
	nucleus varchar(52),
	eventservice smallint,
	failedattempt smallint,
	hs06sec bigint,
	gshare varchar(32),
	hs06 bigint,
	totrchar bigint,
	totwchar bigint,
	totrbytes bigint,
	totwbytes bigint,
	raterchar bigint,
	ratewchar bigint,
	raterbytes bigint,
	ratewbytes bigint,
	resource_type varchar(56),
	diskio integer,
	memory_leak bigint,
	memory_leak_x2 decimal(14,3),
	container_name varchar(200),
	job_label varchar(20),
	meancorecount decimal(8,2),
	gco2_regional decimal(10,2),
	gco2_global decimal(10,2)
) ;
COMMENT ON COLUMN jobsarchived.avgpss IS E'Average PSS in the job';
COMMENT ON COLUMN jobsarchived.avgrss IS E'AverageÂ RSS in the job';
COMMENT ON COLUMN jobsarchived.avgswap IS E'Average SWAP in the job';
COMMENT ON COLUMN jobsarchived.avgvmem IS E'Average VMEM in the job';
COMMENT ON COLUMN jobsarchived.diskio IS E'Local disk access in kBPerSec. Required to limit the number of running jobs based on total IO for each queue.';
COMMENT ON COLUMN jobsarchived.eventservice IS E'The job uses Event Service';
COMMENT ON COLUMN jobsarchived.failedattempt IS E'How many times the input files were failed so far. The maximum number is used if there are multiple input files';
COMMENT ON COLUMN jobsarchived.gshare IS E'Global share';
COMMENT ON COLUMN jobsarchived.hs06 IS E'Core count x core power';
COMMENT ON COLUMN jobsarchived.hs06sec IS E'The product of HS06 score and CPU consumption time';
COMMENT ON COLUMN jobsarchived.maxpss IS E'Maximum PSS in the job';
COMMENT ON COLUMN jobsarchived.maxrss IS E'Maximum RSS in the job';
COMMENT ON COLUMN jobsarchived.maxswap IS E'Maximum SWAP in the job';
COMMENT ON COLUMN jobsarchived.maxvmem IS E'Maximum VMEM in the job';
COMMENT ON COLUMN jobsarchived.maxwalltime IS E'Estimated walltime limit for the job';
COMMENT ON COLUMN jobsarchived.memory_leak IS E'Memory leak in KB/s';
COMMENT ON COLUMN jobsarchived.memory_leak_x2 IS E'Memory leak square statistic';
COMMENT ON COLUMN jobsarchived.nucleus IS E'Name of the site where the job is assigned in WORLD cloud';
COMMENT ON COLUMN jobsarchived.raterbytes IS E'Read bytes rate';
COMMENT ON COLUMN jobsarchived.raterchar IS E'Read chars rate';
COMMENT ON COLUMN jobsarchived.ratewbytes IS E'Write bytes rate';
COMMENT ON COLUMN jobsarchived.ratewchar IS E'Write chars rate';
COMMENT ON COLUMN jobsarchived.totrbytes IS E'Total read bytes';
COMMENT ON COLUMN jobsarchived.totrchar IS E'Total read chars';
COMMENT ON COLUMN jobsarchived.totwbytes IS E'Total write bytes';
COMMENT ON COLUMN jobsarchived.totwchar IS E'Total write chars';
ALTER  TABLE jobsarchived OWNER TO panda;
CREATE INDEX jobsarchived_reqid_idx ON jobsarchived (reqid);
CREATE INDEX jobs_batchid_idx ON jobsarchived (batchid);
CREATE INDEX jobs_comsite_3attr_pandaid_idx ON jobsarchived (computingsite, jobstatus, prodsourcelabel, processingtype, pandaid);
CREATE INDEX jobs_exeerrorcode_idx ON jobsarchived (exeerrorcode);
CREATE INDEX jobs_jeditaskid_pandaid_idx ON jobsarchived (jeditaskid, pandaid);
CREATE INDEX jobs_jobdefid_produsername_idx ON jobsarchived (jobdefinitionid, produsername);
CREATE INDEX jobs_jobname_idx ON jobsarchived (jobname);
CREATE INDEX jobs_jobsetid_produsername_idx ON jobsarchived (jobsetid, produsername);
CREATE INDEX jobs_pandaid_idx ON jobsarchived (pandaid);
CREATE INDEX jobs_produsername_4attr_idx ON jobsarchived (produsername, jobstatus, prodsourcelabel, jobsetid, jobdefinitionid);
CREATE INDEX jobs_specialhandling_idx ON jobsarchived (specialhandling);
CREATE INDEX jobs_statechangetime_idx ON jobsarchived (statechangetime);
CREATE INDEX jobs_taskid_3attr_pandaid_idx ON jobsarchived (taskid, prodsourcelabel, jobstatus, processingtype, pandaid);
CREATE INDEX jobs_upper_produsername_idx ON jobsarchived (upper(produsername));
CREATE INDEX job_prodlabel_status_idx ON jobsarchived (prodsourcelabel, jobstatus);
ALTER TABLE jobsarchived ALTER COLUMN PANDAID SET NOT NULL;
ALTER TABLE jobsarchived ALTER COLUMN JOBDEFINITIONID SET NOT NULL;
ALTER TABLE jobsarchived ALTER COLUMN CREATIONTIME SET NOT NULL;
ALTER TABLE jobsarchived ALTER COLUMN MODIFICATIONTIME SET NOT NULL;
ALTER TABLE jobsarchived ALTER COLUMN ASSIGNEDPRIORITY SET NOT NULL;
ALTER TABLE jobsarchived ALTER COLUMN CURRENTPRIORITY SET NOT NULL;
ALTER TABLE jobsarchived ALTER COLUMN ATTEMPTNR SET NOT NULL;
ALTER TABLE jobsarchived ALTER COLUMN MAXATTEMPT SET NOT NULL;
ALTER TABLE jobsarchived ALTER COLUMN JOBSTATUS SET NOT NULL;
ALTER TABLE jobsarchived ALTER COLUMN MAXCPUCOUNT SET NOT NULL;
ALTER TABLE jobsarchived ALTER COLUMN MAXDISKCOUNT SET NOT NULL;
ALTER TABLE jobsarchived ALTER COLUMN MINRAMCOUNT SET NOT NULL;
ALTER TABLE jobsarchived ALTER COLUMN PILOTERRORCODE SET NOT NULL;
ALTER TABLE jobsarchived ALTER COLUMN EXEERRORCODE SET NOT NULL;
ALTER TABLE jobsarchived ALTER COLUMN SUPERRORCODE SET NOT NULL;
ALTER TABLE jobsarchived ALTER COLUMN DDMERRORCODE SET NOT NULL;
ALTER TABLE jobsarchived ALTER COLUMN BROKERAGEERRORCODE SET NOT NULL;
ALTER TABLE jobsarchived ALTER COLUMN JOBDISPATCHERERRORCODE SET NOT NULL;
ALTER TABLE jobsarchived ALTER COLUMN TASKBUFFERERRORCODE SET NOT NULL;


CREATE TABLE metatable_arch (
	pandaid bigint NOT NULL DEFAULT '0',
	modificationtime timestamp NOT NULL DEFAULT LOCALTIMESTAMP,
	metadata text
) ;
ALTER  TABLE metatable_arch OWNER TO panda;
CREATE INDEX meta_arch_pandaid_idx ON metatable_arch (pandaid);
ALTER TABLE metatable_arch ALTER COLUMN PANDAID SET NOT NULL;
ALTER TABLE metatable_arch ALTER COLUMN MODIFICATIONTIME SET NOT NULL;


CREATE TABLE pandaids_modiftime_errlog_old (
	ora_err_number$ bigint,
	ora_err_mesg$ varchar(2000),
	ora_err_rowid$ oid,
	ora_err_optyp$ varchar(2),
	ora_err_tag$ varchar(2000),
	pandaid varchar(4000),
	modiftime varchar(4000)
) ;
COMMENT ON TABLE pandaids_modiftime_errlog_old IS E'DML Error Logging table for "ATLAS_PANDAARCH"."PANDAIDS_MODIFTIME"';
ALTER  TABLE pandaids_modiftime_errlog_old OWNER TO panda;


CREATE TABLE pandaids_modiftime_old (
	pandaid bigint NOT NULL,
	modiftime timestamp NOT NULL
) ;
ALTER  TABLE pandaids_modiftime_old OWNER TO panda;
ALTER TABLE pandaids_modiftime_old ADD PRIMARY KEY (pandaid,modiftime);


CREATE TABLE table_part_boundaries (
	tab_name varchar(30) NOT NULL,
	part_name varchar(30) NOT NULL,
	part_position bigint,
	part_boundary_dictionary text,
	part_boundary timestamp,
	last_created_view varchar(30)
) ;
ALTER  TABLE table_part_boundaries OWNER TO panda;
ALTER TABLE table_part_boundaries ADD PRIMARY KEY (tab_name,part_name);
