-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.2
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:ADCR

SET client_encoding TO 'UTF8';

SET search_path = doma_pandameta,public;
\set ON_ERROR_STOP ON

SET check_function_bodies = false;

CREATE SCHEMA IF NOT EXISTS doma_pandameta;
CREATE SEQUENCE proxykey_id_seq INCREMENT 1 MINVALUE 1 NO MAXVALUE START 1;
ALTER SEQUENCE proxykey_id_seq OWNER TO panda;
CREATE SEQUENCE siteaccess_id_seq INCREMENT 1 MINVALUE 1 NO MAXVALUE START 1;
ALTER SEQUENCE siteaccess_id_seq OWNER TO panda;
CREATE SEQUENCE users_id_seq INCREMENT 1 MINVALUE 1 NO MAXVALUE START 1;
ALTER SEQUENCE users_id_seq OWNER TO panda;
