-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.2
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:ADCR

SET client_encoding TO 'UTF8';

SET search_path = doma_pandaarch,public;
\set ON_ERROR_STOP ON

SET check_function_bodies = false;





CREATE OR REPLACE PROCEDURE atlas_pandaarch.do_grants (obj_type text, obj_name text,owner_name text) AS $body$
DECLARE

	
	
	privs varchar(100);
BEGIN

	 -- need to put " " around the object names, because some users create the objects with preserved character case.
	IF (obj_name NOT IN ('DO_GRANTS','GRANTS_UPDATE','CREATE_SYN4EXIST_OBJ') AND substr(obj_name,1,4)<>'BIN$') THEN

		IF obj_type IN ('TABLE') THEN
        	 	EXECUTE 'GRANT SELECT,INSERT,UPDATE,DELETE on "'||obj_name||'" to ATLAS_PANDA_WRITEROLE';
		        EXECUTE 'GRANT SELECT on "'||obj_name||'" to ATLAS_PANDA_READROLE';
		elsif obj_type = 'SEQUENCE' THEN
	        	EXECUTE 'GRANT SELECT on "'||obj_name||'" to ATLAS_PANDA_WRITEROLE';
		        EXECUTE 'GRANT SELECT on "'||obj_name||'" to ATLAS_PANDA_READROLE';
		elsif obj_type IN ('VIEW', 'MATERIALIZED VIEW') THEN
			privs := ' SELECT,INSERT,UPDATE,DELETE ';
			FOR i IN 1..2 LOOP /*if fails on the first loop with error 01720, then goes to the EXEPTION and changes the statement */
				BEGIN
					EXECUTE 'GRANT '|| privs ||' on "'|| obj_name||'" to ATLAS_PANDA_WRITEROLE';
				        EXECUTE 'GRANT SELECT on "'||obj_name||'" to ATLAS_PANDA_READROLE';
					EXIT;
				EXCEPTION
					WHEN SQLSTATE '50001' THEN
						privs := ' SELECT ';
				END;
			END LOOP;
		elsif obj_type IN ('PROCEDURE', 'PACKAGE','FUNCTION', 'TYPE') AND obj_name <> 'CREATE_SYN' THEN
	         	EXECUTE 'GRANT EXECUTE on "'||obj_name||'" to ATLAS_PANDA_WRITEROLE';
		        EXECUTE 'GRANT EXECUTE on "'||obj_name||'" to ATLAS_PANDA_READROLE';
		END IF;
	END IF;
END;
$body$
LANGUAGE PLPGSQL
;
ALTER PROCEDURE atlas_pandaarch.do_grants (obj_type text, obj_name text,owner_name text) OWNER TO panda;
-- REVOKE ALL ON PROCEDURE atlas_pandaarch.do_grants (obj_type text, obj_name text,owner_name text) FROM PUBLIC;





CREATE OR REPLACE PROCEDURE atlas_pandaarch.generate_timerange_views ( name_table text, period_days bigint, name_view text) AS $body$
DECLARE


j bigint;
m_table varchar(30);
name_part varchar(30);
stmt varchar(32000);
TYPE part_names IS TABLE OF varchar(30) INDEX BY integer;
coll_parts part_names;


BEGIN

  -- m_table := DBMS_ASSERT.QUALIFIED_SQL_NAME(name_table);
  -- The DBMS_ASSERT.SIMPLE_SQL_NAME function checks the input string conforms to the basic characteristics of a simple SQL name.
  m_table := DBMS_ASSERT.SIMPLE_SQL_NAME(name_table);

  DELETE FROM ATLAS_PANDAARCH.table_part_boundaries WHERE tab_name = UPPER(m_table);

  INSERT INTO ATLAS_PANDAARCH.table_part_boundaries(tab_name, part_name, part_position, part_boundary_dictionary )
  SELECT table_name, partition_name, partition_position , TO_LOB(high_value)
  FROM USER_tab_partitions
  WHERE table_name = UPPER(m_table)
  ORDER BY partition_position;

  UPDATE ATLAS_PANDAARCH.table_part_boundaries SET part_boundary = TO_DATE(substr(part_boundary_dictionary, 11, 19), 'YYYY-MM-DD HH24:MI:SS');

	-- get the partition names for a given time range. The OR clause is needed in order to catch the partition of the current day
	SELECT part_name BULK COLLECT INTO STRICT coll_parts
	FROM ATLAS_PANDAARCH.table_part_boundaries
	WHERE tab_name = UPPER(m_table) AND
	(
	    (clock_timestamp() >= part_boundary AND clock_timestamp() - period_days <= part_boundary )
	    OR
	(part_boundary = ( SELECT MIN(part_boundary) FROM ATLAS_PANDAARCH.table_part_boundaries WHERE part_boundary > clock_timestamp() ) )
	)
	ORDER BY PART_POSITION;

	-- The DBMS_ASSERT.ENQUOTE_NAME function encloses the input string (the view name) within double quotes, unless they are already present
	stmt := 'CREATE OR REPLACE VIEW ATLAS_PANDAARCH.' || DBMS_ASSERT.ENQUOTE_NAME(name_view, capitalize=> TRUE) || ' AS ( ';

	IF coll_parts.COUNT > 0 THEN
		FOR j in 1..coll_parts.LAST-1 LOOP
			-- DBMS_OUTPUT.put_line(coll_parts(j));
			stmt := stmt || 'SELECT * FROM ATLAS_PANDAARCH.' ||UPPER(m_table)|| ' partition (' || coll_parts(j) || ') UNION ALL ';

			UPDATE ATLAS_PANDAARCH.table_part_boundaries SET last_created_view = name_view
				WHERE tab_name = UPPER(m_table) AND part_name = coll_parts(j);
		END LOOP;

		-- for the last partition in the collection:
		stmt := stmt || ' SELECT * FROM ATLAS_PANDAARCH.' ||UPPER(m_table)|| ' partition (' || coll_parts(coll_parts.LAST) || ')  ) WITH READ ONLY ';

		name_part := coll_parts(coll_parts.LAST);
		UPDATE ATLAS_PANDAARCH.table_part_boundaries SET last_created_view = name_view
			WHERE tab_name = UPPER(m_table) AND part_name = name_part;

		-- DBMS_OUTPUT.put_line(stmt);
		-- execute the create view statement
		EXECUTE stmt;
	END IF;
	COMMIT;
END;
$body$
LANGUAGE PLPGSQL
;
ALTER PROCEDURE atlas_pandaarch.generate_timerange_views ( name_table text, period_days bigint, name_view text) OWNER TO panda;
-- REVOKE ALL ON PROCEDURE atlas_pandaarch.generate_timerange_views ( name_table text, period_days bigint, name_view text) FROM PUBLIC;





CREATE OR REPLACE PROCEDURE atlas_pandaarch.grant_privs4exist_obj (owner_name text ) AS $body$
DECLARE

	
	
	privs varchar(100);
  rec RECORD;
BEGIN
 -- need to put " " around the object names, because some users create the objects with preserved character case.
	-- IMPORTANT - GRANT OBJECT PRIVILEGES FIRST TO THE TABLES
	FOR rec in (SELECT object_name as obj_name, object_type as obj_type FROM all_objects WHERE owner = 'ATLAS_PANDAARCH' AND object_type = 'TABLE' AND substr(object_name,1,4)<>'BIN$' AND  substr(object_name,1,12)<>'SYS_IOT_OVER') LOOP
       	 	EXECUTE 'GRANT SELECT,INSERT,UPDATE,DELETE on "'||rec.obj_name||'" to ATLAS_PANDA_WRITEROLE';
	        EXECUTE 'GRANT SELECT on "'||rec.obj_name||'" to ATLAS_PANDA_READROLE';
	END LOOP;

	FOR rec in (SELECT object_name as obj_name, object_type as obj_type FROM all_objects WHERE owner = 'ATLAS_PANDAARCH' AND object_type IN ('VIEW','SEQUENCE','PROCEDURE', 'PACKAGE', 'FUNCTION', 'MATERIALIZED VIEW', 'TYPE' ) ORDER BY object_type DESC ) LOOP

		IF rec.obj_name NOT IN ('DO_GRANTS','GRANTS_UPDATE','GRANT_PRIVS4EXIST_OBJ') THEN
			IF rec.obj_type IN ('VIEW', 'MATERIALIZED VIEW' ) THEN
				privs := ' SELECT,INSERT,UPDATE,DELETE ';
				FOR i IN 1..2 LOOP /*if fails on the first loop with error 01720, then goes to the EXEPTION and changes the statement */
					BEGIN
						EXECUTE 'GRANT '|| privs ||' on "'||rec.obj_name||'" to ATLAS_PANDA_WRITEROLE';
					        EXECUTE 'GRANT SELECT on "'||rec.obj_name||'" to ATLAS_PANDA_READROLE';
						EXIT;
					EXCEPTION
						WHEN SQLSTATE '50001' THEN
						privs := ' SELECT ';
					END;
				END LOOP;
			elsif rec.obj_type = 'SEQUENCE' THEN
	        		EXECUTE 'GRANT SELECT on "'||rec.obj_name||'" to ATLAS_PANDA_WRITEROLE';
			        EXECUTE 'GRANT SELECT on "'||rec.obj_name||'" to ATLAS_PANDA_READROLE';
			elsif rec.obj_type IN ('PROCEDURE', 'PACKAGE','FUNCTION', 'TYPE') AND rec.obj_name <> 'CREATE_SYN' THEN
		         	EXECUTE 'GRANT EXECUTE on "'||rec.obj_name||'" to ATLAS_PANDA_WRITEROLE';
			        EXECUTE 'GRANT EXECUTE on "'||rec.obj_name||'" to ATLAS_PANDA_READROLE';
			END IF;
		END IF;
	END LOOP;
END;
$body$
LANGUAGE PLPGSQL
;
ALTER PROCEDURE atlas_pandaarch.grant_privs4exist_obj (owner_name text ) OWNER TO panda;
-- REVOKE ALL ON PROCEDURE atlas_pandaarch.grant_privs4exist_obj (owner_name text ) FROM PUBLIC;

