-- Generated by Ora2Pg, the Oracle database Schema converter, version 21.1
-- Copyright 2000-2020 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:PDBR

SET client_encoding TO 'UTF8';

SET search_path = doma_pandabigmon,public;
\set ON_ERROR_STOP ON

SET check_function_bodies = false;



CREATE OR REPLACE FUNCTION doma_pandabigmon.geths06ssummary (CONDITION text) RETURNS HS06SSUMMARY_T AS $body$
DECLARE

coll HS06SSUMMARY_T;
sqlstatement varchar(32767);

BEGIN

sqlstatement := '
select DOMA_PANDABIGMON.HS06S_T(h.nucleus, h.COMPUTINGSITE, h.usedhs06spersite, h.failedhs06spersite) 
from (
select nucleus, COMPUTINGSITE, 
sum(usedhs06spertask) as usedhs06spersite, 
sum(failedhs06spertask) as failedhs06spersite 
from (
select jj.nucleus, jj.COMPUTINGSITE,  (ceil(sum(hs06perjob)*1.5*max(hs06perjob)/avg(hs06perjob))) as usedhs06spertask,
case when jobstatus=''failed'' then (ceil(sum(hs06perjob)*1.5*max(hs06perjob)/avg(hs06perjob))) end  as failedhs06spertask 
from (
select jt.NUCLEUS, jt.COMPUTINGSITE, jt.jobstatus, ((jt.jobduration-ts.BASEWALLTIME)*jt.sitecoef*ts.CPUEFFICIENCY/100) as hs06perjob from (
(select t.NUCLEUS, t.COMPUTINGSITE, t.JEDITASKID, t.jobstatus, (t.ENDTIME-t.STARTTIME)*24*60*60 as jobduration, case when s.corecount is null then s.COREPOWER else (s.CORECOUNT*s.COREPOWER) end as sitecoef  from 
DOMA_PANDA.JOBSARCHIVED4 t 
INNER JOIN 
DOMA_PANDAMETA.SCHEDCONFIG s 
ON t.COMPUTINGSITE=s.SITEID
where t.MODIFICATIONTIME>=(sysdate-3) and t.CLOUD=''WORLD'' and t.JOBSTATUS in (''finished'',''failed'') and '|| CONDITION ||'
)) jt 
INNER JOIN
DOMA_PANDA.JEDI_TASKS ts 
ON ts.JEDITASKID = jt.JEDITASKID
) jj
where hs06perjob>0
group by jj.COMPUTINGSITE, jj.jobstatus, jj.nucleus
) 
group by COMPUTINGSITE, nucleus
order by nucleus) h';

EXECUTE sqlstatement BULK COLLECT INTO STRICT coll;
RETURN coll;
END;
$body$
LANGUAGE PLPGSQL
;
ALTER FUNCTION geths06ssummary (CONDITION text) OWNER TO panda;
-- REVOKE ALL ON FUNCTION doma_pandabigmon.geths06ssummary (CONDITION text) FROM PUBLIC;

