-- Generated by Ora2Pg, the Oracle database Schema converter, version 21.1
-- Copyright 2000-2020 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:PDBR

SET client_encoding TO 'UTF8';

SET search_path = doma_pandabigmon,public;
\set ON_ERROR_STOP ON

SET check_function_bodies = false;


CREATE TYPE hs06s_t AS (
NUCLEUS varchar(200)
, COMPUTINGSITE  varchar(200)
, USEDHS06SPERSITE bigint
, FAILEDHS06SPERSITE bigint

);
ALTER TYPE hs06s_t OWNER TO panda;

CREATE TYPE hs06ssummary_t AS (hs06ssummary_t HS06S_T[]);
ALTER TYPE hs06ssummary_t OWNER TO panda;

CREATE TYPE pandamon_jobpage_obj AS (
     PANDA_ATTRIBUTE VARCHAR(100),
     ATTR_VALUE VARCHAR(300),
     NUM_OCCURRENCES bigint
 );
 ALTER TYPE pandamon_jobpage_obj OWNER TO panda;

 CREATE TYPE pandamon_jobspage_coll AS (pandamon_jobspage_coll pandamon_jobpage_obj[]);
 ALTER TYPE pandamon_jobspage_coll OWNER TO panda;
