INSERT INTO DOMA_PANDA.JEDI_WORK_QUEUE (QUEUE_ID,QUEUE_NAME,QUEUE_TYPE,VO,QUEUE_FUNCTION)
    VALUES(1,'test','test','wlcg','Resource');
INSERT INTO DOMA_PANDA.JEDI_WORK_QUEUE (QUEUE_ID,QUEUE_NAME,QUEUE_TYPE,VO,QUEUE_FUNCTION)
    VALUES(2,'managed','managed','wlcg','Resource');
INSERT INTO DOMA_PANDA.JEDI_WORK_QUEUE (QUEUE_ID,QUEUE_NAME,QUEUE_TYPE,VO,QUEUE_FUNCTION)
    VALUES(3,'user','user','wlcg','Resource');
INSERT INTO DOMA_PANDA.RESOURCE_TYPES (RESOURCE_NAME,MINCORE) VALUES('Undefined',1);
INSERT INTO DOMA_PANDA.CONFIG (APP,COMPONENT,KEY,VALUE,TYPE,VO,DESCR)
    VALUES('pandaserver','job_timeout','TIMEOUT_defined','30','int','wlcg','timeout for defined jobs');
INSERT INTO DOMA_PANDA.CONFIG (APP,COMPONENT,KEY,VALUE,TYPE,VO,DESCR)
    VALUES('pandaserver','job_timeout','TIMEOUT_holding','30','int','wlcg','timeout for holding jobs');
