--------------------------------------------------------
--  File created - Thursday-November-17-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence ALL_REQUESTS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ATLAS_PANDABIGMON"."ALL_REQUESTS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 5 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT SELECT ON "ATLAS_PANDABIGMON"."ALL_REQUESTS_SEQ" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."ALL_REQUESTS_SEQ" TO "ATLAS_PANDABIGMON_R";
--------------------------------------------------------
--  DDL for Sequence ART_RESULTS_QUEUE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ATLAS_PANDABIGMON"."ART_RESULTS_QUEUE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT SELECT ON "ATLAS_PANDABIGMON"."ART_RESULTS_QUEUE_SEQ" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."ART_RESULTS_QUEUE_SEQ" TO "ATLAS_PANDABIGMON_R";
--------------------------------------------------------
--  DDL for Sequence ART_RESULTS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ATLAS_PANDABIGMON"."ART_RESULTS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT SELECT ON "ATLAS_PANDABIGMON"."ART_RESULTS_SEQ" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."ART_RESULTS_SEQ" TO "ATLAS_PANDABIGMON_R";
--------------------------------------------------------
--  DDL for Sequence AUTH_GROUP_PERMISSIONS_SQ
--------------------------------------------------------

   CREATE SEQUENCE  "ATLAS_PANDABIGMON"."AUTH_GROUP_PERMISSIONS_SQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT SELECT ON "ATLAS_PANDABIGMON"."AUTH_GROUP_PERMISSIONS_SQ" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."AUTH_GROUP_PERMISSIONS_SQ" TO "ATLAS_PANDABIGMON_R";
--------------------------------------------------------
--  DDL for Sequence AUTH_GROUP_SQ
--------------------------------------------------------

   CREATE SEQUENCE  "ATLAS_PANDABIGMON"."AUTH_GROUP_SQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT SELECT ON "ATLAS_PANDABIGMON"."AUTH_GROUP_SQ" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."AUTH_GROUP_SQ" TO "ATLAS_PANDABIGMON_R";
--------------------------------------------------------
--  DDL for Sequence AUTH_PERMISSION_SQ
--------------------------------------------------------

   CREATE SEQUENCE  "ATLAS_PANDABIGMON"."AUTH_PERMISSION_SQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT SELECT ON "ATLAS_PANDABIGMON"."AUTH_PERMISSION_SQ" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."AUTH_PERMISSION_SQ" TO "ATLAS_PANDABIGMON_R";
--------------------------------------------------------
--  DDL for Sequence AUTH_USER_GROUPS_SQ
--------------------------------------------------------

   CREATE SEQUENCE  "ATLAS_PANDABIGMON"."AUTH_USER_GROUPS_SQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT SELECT ON "ATLAS_PANDABIGMON"."AUTH_USER_GROUPS_SQ" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."AUTH_USER_GROUPS_SQ" TO "ATLAS_PANDABIGMON_R";
--------------------------------------------------------
--  DDL for Sequence AUTH_USER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ATLAS_PANDABIGMON"."AUTH_USER_SEQ"  MINVALUE 1 MAXVALUE 99999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT SELECT ON "ATLAS_PANDABIGMON"."AUTH_USER_SEQ" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."AUTH_USER_SEQ" TO "ATLAS_PANDABIGMON_R";
--------------------------------------------------------
--  DDL for Sequence AUTH_USER_SQ
--------------------------------------------------------

   CREATE SEQUENCE  "ATLAS_PANDABIGMON"."AUTH_USER_SQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT SELECT ON "ATLAS_PANDABIGMON"."AUTH_USER_SQ" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."AUTH_USER_SQ" TO "ATLAS_PANDABIGMON_R";
--------------------------------------------------------
--  DDL for Sequence AUTH_USER_USER_PERMISSI7B1E
--------------------------------------------------------

   CREATE SEQUENCE  "ATLAS_PANDABIGMON"."AUTH_USER_USER_PERMISSI7B1E"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT SELECT ON "ATLAS_PANDABIGMON"."AUTH_USER_USER_PERMISSI7B1E" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."AUTH_USER_USER_PERMISSI7B1E" TO "ATLAS_PANDABIGMON_R";
--------------------------------------------------------
--  DDL for Sequence DJANGO_CONTENT_TYPE_SQ
--------------------------------------------------------

   CREATE SEQUENCE  "ATLAS_PANDABIGMON"."DJANGO_CONTENT_TYPE_SQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT SELECT ON "ATLAS_PANDABIGMON"."DJANGO_CONTENT_TYPE_SQ" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."DJANGO_CONTENT_TYPE_SQ" TO "ATLAS_PANDABIGMON_R";
--------------------------------------------------------
--  DDL for Sequence DJANGO_MIGRATIONS_SQ
--------------------------------------------------------

   CREATE SEQUENCE  "ATLAS_PANDABIGMON"."DJANGO_MIGRATIONS_SQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT SELECT ON "ATLAS_PANDABIGMON"."DJANGO_MIGRATIONS_SQ" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."DJANGO_MIGRATIONS_SQ" TO "ATLAS_PANDABIGMON_R";
--------------------------------------------------------
--  DDL for Sequence MLFLOW_CONTAINERS_SEQ_ID
--------------------------------------------------------

   CREATE SEQUENCE  "ATLAS_PANDABIGMON"."MLFLOW_CONTAINERS_SEQ_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT SELECT ON "ATLAS_PANDABIGMON"."MLFLOW_CONTAINERS_SEQ_ID" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."MLFLOW_CONTAINERS_SEQ_ID" TO "ATLAS_PANDABIGMON_R";
--------------------------------------------------------
--  DDL for Sequence OBJECTS_COMPARISON_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ATLAS_PANDABIGMON"."OBJECTS_COMPARISON_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT SELECT ON "ATLAS_PANDABIGMON"."OBJECTS_COMPARISON_SEQ" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."OBJECTS_COMPARISON_SEQ" TO "ATLAS_PANDABIGMON_R";

--------------------------------------------------------
--  DDL for Sequence PANDAMON_REQUEST_TOKEN_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ATLAS_PANDABIGMON"."PANDAMON_REQUEST_TOKEN_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT SELECT ON "ATLAS_PANDABIGMON"."PANDAMON_REQUEST_TOKEN_SEQ" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."PANDAMON_REQUEST_TOKEN_SEQ" TO "ATLAS_PANDABIGMON_R";

--------------------------------------------------------
--  DDL for Sequence PROD_NEVENTS_HISTORY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ATLAS_PANDABIGMON"."PROD_NEVENTS_HISTORY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT SELECT ON "ATLAS_PANDABIGMON"."PROD_NEVENTS_HISTORY_SEQ" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."PROD_NEVENTS_HISTORY_SEQ" TO "ATLAS_PANDABIGMON_R";
--------------------------------------------------------
--  DDL for Sequence REJECTED_REQUEST_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ATLAS_PANDABIGMON"."REJECTED_REQUEST_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT SELECT ON "ATLAS_PANDABIGMON"."REJECTED_REQUEST_SEQ" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."REJECTED_REQUEST_SEQ" TO "ATLAS_PANDABIGMON_R";
--------------------------------------------------------
--  DDL for Sequence REPORT_EMAIL_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ATLAS_PANDABIGMON"."REPORT_EMAIL_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT SELECT ON "ATLAS_PANDABIGMON"."REPORT_EMAIL_SEQ" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."REPORT_EMAIL_SEQ" TO "ATLAS_PANDABIGMON_R";
--------------------------------------------------------
--  DDL for Sequence REQUEST_STATS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ATLAS_PANDABIGMON"."REQUEST_STATS_SEQ"  MINVALUE 1 MAXVALUE 999999999 INCREMENT BY 1 START WITH 1 CACHE 2 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT SELECT ON "ATLAS_PANDABIGMON"."REQUEST_STATS_SEQ" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."REQUEST_STATS_SEQ" TO "ATLAS_PANDABIGMON_R";
--------------------------------------------------------
--  DDL for Sequence RUCIO_ACCOUNTS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ATLAS_PANDABIGMON"."RUCIO_ACCOUNTS_SEQ"  MINVALUE 1 MAXVALUE 999999999 INCREMENT BY 1 START WITH 1 CACHE 2 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT SELECT ON "ATLAS_PANDABIGMON"."RUCIO_ACCOUNTS_SEQ" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."RUCIO_ACCOUNTS_SEQ" TO "ATLAS_PANDABIGMON_R";
--------------------------------------------------------
--  DDL for Sequence SOCIAL_AUTH_ASSOCIATION_SQ
--------------------------------------------------------

   CREATE SEQUENCE  "ATLAS_PANDABIGMON"."SOCIAL_AUTH_ASSOCIATION_SQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT SELECT ON "ATLAS_PANDABIGMON"."SOCIAL_AUTH_ASSOCIATION_SQ" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."SOCIAL_AUTH_ASSOCIATION_SQ" TO "ATLAS_PANDABIGMON_R";
--------------------------------------------------------
--  DDL for Sequence SOCIAL_AUTH_CODE_SQ
--------------------------------------------------------

   CREATE SEQUENCE  "ATLAS_PANDABIGMON"."SOCIAL_AUTH_CODE_SQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT SELECT ON "ATLAS_PANDABIGMON"."SOCIAL_AUTH_CODE_SQ" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."SOCIAL_AUTH_CODE_SQ" TO "ATLAS_PANDABIGMON_R";
--------------------------------------------------------
--  DDL for Sequence SOCIAL_AUTH_NONCE_SQ
--------------------------------------------------------

   CREATE SEQUENCE  "ATLAS_PANDABIGMON"."SOCIAL_AUTH_NONCE_SQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT SELECT ON "ATLAS_PANDABIGMON"."SOCIAL_AUTH_NONCE_SQ" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."SOCIAL_AUTH_NONCE_SQ" TO "ATLAS_PANDABIGMON_R";
--------------------------------------------------------
--  DDL for Sequence SOCIAL_AUTH_PARTIAL_SQ
--------------------------------------------------------

   CREATE SEQUENCE  "ATLAS_PANDABIGMON"."SOCIAL_AUTH_PARTIAL_SQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT SELECT ON "ATLAS_PANDABIGMON"."SOCIAL_AUTH_PARTIAL_SQ" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."SOCIAL_AUTH_PARTIAL_SQ" TO "ATLAS_PANDABIGMON_R";
--------------------------------------------------------
--  DDL for Sequence SOCIAL_AUTH_USERSOCIALA0419
--------------------------------------------------------

   CREATE SEQUENCE  "ATLAS_PANDABIGMON"."SOCIAL_AUTH_USERSOCIALA0419"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT SELECT ON "ATLAS_PANDABIGMON"."SOCIAL_AUTH_USERSOCIALA0419" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."SOCIAL_AUTH_USERSOCIALA0419" TO "ATLAS_PANDABIGMON_R";
--------------------------------------------------------
--  DDL for Sequence USERS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ATLAS_PANDABIGMON"."USERS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT SELECT ON "ATLAS_PANDABIGMON"."USERS_SEQ" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."USERS_SEQ" TO "ATLAS_PANDABIGMON_R";
--------------------------------------------------------
--  DDL for Sequence USER_SETTINGS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ATLAS_PANDABIGMON"."USER_SETTINGS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT SELECT ON "ATLAS_PANDABIGMON"."USER_SETTINGS_SEQ" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."USER_SETTINGS_SEQ" TO "ATLAS_PANDABIGMON_R";
--------------------------------------------------------
--  DDL for Sequence USER_SETTINGS_SQ
--------------------------------------------------------

   CREATE SEQUENCE  "ATLAS_PANDABIGMON"."USER_SETTINGS_SQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT SELECT ON "ATLAS_PANDABIGMON"."USER_SETTINGS_SQ" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."USER_SETTINGS_SQ" TO "ATLAS_PANDABIGMON_R";
--------------------------------------------------------
--  DDL for Sequence VISITS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ATLAS_PANDABIGMON"."VISITS_SEQ"  MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT SELECT ON "ATLAS_PANDABIGMON"."VISITS_SEQ" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."VISITS_SEQ" TO "ATLAS_PANDABIGMON_R";
