--------------------------------------------------------
--  File created - Thursday-November-17-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Type HS06SSUMMARY_T
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "ATLAS_PANDABIGMON"."HS06SSUMMARY_T" AS TABLE OF HS06S_T;

/

  GRANT EXECUTE ON "ATLAS_PANDABIGMON"."HS06SSUMMARY_T" TO "ATLAS_PANDABIGMON_W";
  GRANT EXECUTE ON "ATLAS_PANDABIGMON"."HS06SSUMMARY_T" TO "ATLAS_PANDABIGMON_R";
--------------------------------------------------------
--  DDL for Type HS06S_T
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "ATLAS_PANDABIGMON"."HS06S_T" AS OBJECT 
( 
  NUCLEUS VARCHAR2(200 BYTE)
, COMPUTINGSITE  VARCHAR2(200 BYTE)
, USEDHS06SPERSITE NUMBER(20, 0)
, FAILEDHS06SPERSITE NUMBER(20, 0)
)

/

  GRANT EXECUTE ON "ATLAS_PANDABIGMON"."HS06S_T" TO "ATLAS_PANDABIGMON_R";
  GRANT EXECUTE ON "ATLAS_PANDABIGMON"."HS06S_T" TO "ATLAS_PANDABIGMON_W";
--------------------------------------------------------
--  DDL for Type PANDAMON_JOBSPAGE_COLL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "ATLAS_PANDABIGMON"."PANDAMON_JOBSPAGE_COLL" AS TABLE OF ATLAS_PANDABIGMON.PANDAMON_JOBSPAGE_OBJ;

/

  GRANT EXECUTE ON "ATLAS_PANDABIGMON"."PANDAMON_JOBSPAGE_COLL" TO "ATLAS_PANDABIGMON_W";
  GRANT EXECUTE ON "ATLAS_PANDABIGMON"."PANDAMON_JOBSPAGE_COLL" TO "ATLAS_PANDABIGMON_R";
--------------------------------------------------------
--  DDL for Type PANDAMON_JOBSPAGE_OBJ
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "ATLAS_PANDABIGMON"."PANDAMON_JOBSPAGE_OBJ" AS OBJECT
(
PANDA_ATTRIBUTE VARCHAR2(100),
ATTR_VALUE VARCHAR2(300),
NUM_OCCURRENCES NUMBER(10)
);
--create or replace TYPE ATLAS_PANDABIGMON.PANDAMON_JOBSPAGE_COLL AS TABLE OF ATLAS_PANDABIGMON.PANDAMON_JOBSPAGE_OBJ;

/

  GRANT EXECUTE ON "ATLAS_PANDABIGMON"."PANDAMON_JOBSPAGE_OBJ" TO "ATLAS_PANDABIGMON_W";
  GRANT EXECUTE ON "ATLAS_PANDABIGMON"."PANDAMON_JOBSPAGE_OBJ" TO "ATLAS_PANDABIGMON_R";
