--------------------------------------------------------
--  File created - Thursday-November-17-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ALL_REQUESTS
--------------------------------------------------------

  CREATE TABLE "ATLAS_PANDABIGMON"."ALL_REQUESTS" 
   (	"ID" NUMBER(10,0), 
	"SERVER" VARCHAR2(100 BYTE), 
	"REMOTE" VARCHAR2(100 BYTE), 
	"QTIME" TIMESTAMP (6), 
	"URL" VARCHAR2(2500 BYTE), 
	"REFERRER" VARCHAR2(4000 BYTE), 
	"USERAGENT" VARCHAR2(400 BYTE), 
	"IS_REJECTED" NUMBER(1,0), 
	"URLVIEW" VARCHAR2(300 BYTE)
   );
  GRANT DELETE ON "ATLAS_PANDABIGMON"."ALL_REQUESTS" TO "ATLAS_PANDABIGMON_W";
  GRANT INSERT ON "ATLAS_PANDABIGMON"."ALL_REQUESTS" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."ALL_REQUESTS" TO "ATLAS_PANDABIGMON_W";
  GRANT UPDATE ON "ATLAS_PANDABIGMON"."ALL_REQUESTS" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."ALL_REQUESTS" TO "ATLAS_PANDABIGMON_R";
  GRANT DELETE ON "ATLAS_PANDABIGMON"."ALL_REQUESTS" TO "ATLAS_PANDABIGMON_R";
  GRANT INSERT ON "ATLAS_PANDABIGMON"."ALL_REQUESTS" TO "ATLAS_PANDABIGMON_R";
  GRANT UPDATE ON "ATLAS_PANDABIGMON"."ALL_REQUESTS" TO "ATLAS_PANDABIGMON_R";

--------------------------------------------------------
--  DDL for Table ALL_REQUESTS_DAILY
--------------------------------------------------------

  CREATE TABLE "ATLAS_PANDABIGMON"."ALL_REQUESTS_DAILY" 
   (	"QTIME" TIMESTAMP (6), 
	"REMOTE" VARCHAR2(100 BYTE), 
	"IS_REJECTED" NUMBER(1,0), 
	"SERVER" VARCHAR2(100 BYTE), 
	"URLVIEW" VARCHAR2(300 BYTE), 
	"URL" VARCHAR2(2500 BYTE), 
	"REFERRER" VARCHAR2(4000 BYTE), 
	"USERAGENT" VARCHAR2(400 BYTE), 
	"RTIME" TIMESTAMP (6), 
	"LOAD" NUMBER(10,2), 
	"MEM" NUMBER(10,2), 
	"DBACTIVESESS" NUMBER(5,0), 
	"DBTOTALSESS" NUMBER(5,0), 
	"ID" NUMBER(10,0)
   )
  PARTITION BY RANGE ("QTIME") INTERVAL (NUMTODSINTERVAL(1,'DAY')) 
 (PARTITION "DATA_BEFORE_01012017"  VALUES LESS THAN (TIMESTAMP' 2017-01-01 00:00:00');

   COMMENT ON COLUMN "ATLAS_PANDABIGMON"."ALL_REQUESTS_DAILY"."ID" IS 'Column with no relevance to the other data, but necessary to be present because of the Django framework which expects a primary key or column called ID';
   COMMENT ON TABLE "ATLAS_PANDABIGMON"."ALL_REQUESTS_DAILY"  IS 'Table for storing requests coming from each IP address and used for super fast check (before serving a new request) on whether too many requests are coming from the same remote machine (in which case the request will be discarded)';
  GRANT INSERT ON "ATLAS_PANDABIGMON"."ALL_REQUESTS_DAILY" TO "ATLAS_PANDABIGMON_W";
  GRANT INSERT ON "ATLAS_PANDABIGMON"."ALL_REQUESTS_DAILY" TO "ATLAS_PANDABIGMON_R";
  GRANT UPDATE ON "ATLAS_PANDABIGMON"."ALL_REQUESTS_DAILY" TO "ATLAS_PANDABIGMON_W";
  GRANT UPDATE ON "ATLAS_PANDABIGMON"."ALL_REQUESTS_DAILY" TO "ATLAS_PANDABIGMON_R";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."ALL_REQUESTS_DAILY" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."ALL_REQUESTS_DAILY" TO "ATLAS_PANDABIGMON_R";

--------------------------------------------------------
--  DDL for Table AUTHTOKEN_TOKEN
--------------------------------------------------------

  CREATE TABLE "ATLAS_PANDABIGMON"."AUTHTOKEN_TOKEN" 
   (	"KEY" VARCHAR2(40 BYTE), 
	"USER_ID" VARCHAR2(20 BYTE), 
	"CREATED" DATE DEFAULT CURRENT_TIMESTAMP
   );
  GRANT DELETE ON "ATLAS_PANDABIGMON"."AUTHTOKEN_TOKEN" TO "ATLAS_PANDABIGMON_W";
  GRANT INSERT ON "ATLAS_PANDABIGMON"."AUTHTOKEN_TOKEN" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."AUTHTOKEN_TOKEN" TO "ATLAS_PANDABIGMON_W";
  GRANT UPDATE ON "ATLAS_PANDABIGMON"."AUTHTOKEN_TOKEN" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."AUTHTOKEN_TOKEN" TO "ATLAS_PANDABIGMON_R";
  GRANT DELETE ON "ATLAS_PANDABIGMON"."AUTHTOKEN_TOKEN" TO "ATLAS_PANDABIGMON_R";
  GRANT INSERT ON "ATLAS_PANDABIGMON"."AUTHTOKEN_TOKEN" TO "ATLAS_PANDABIGMON_R";
  GRANT UPDATE ON "ATLAS_PANDABIGMON"."AUTHTOKEN_TOKEN" TO "ATLAS_PANDABIGMON_R";

--------------------------------------------------------
--  DDL for Table AUTH_GROUP
--------------------------------------------------------

  CREATE TABLE "ATLAS_PANDABIGMON"."AUTH_GROUP" 
   (	"ID" NUMBER(11,0), 
	"NAME" NVARCHAR2(80)
   );
  GRANT DELETE ON "ATLAS_PANDABIGMON"."AUTH_GROUP" TO "ATLAS_PANDABIGMON_W";
  GRANT INSERT ON "ATLAS_PANDABIGMON"."AUTH_GROUP" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."AUTH_GROUP" TO "ATLAS_PANDABIGMON_W";
  GRANT UPDATE ON "ATLAS_PANDABIGMON"."AUTH_GROUP" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."AUTH_GROUP" TO "ATLAS_PANDABIGMON_R";
  GRANT DELETE ON "ATLAS_PANDABIGMON"."AUTH_GROUP" TO "ATLAS_PANDABIGMON_R";
  GRANT INDEX ON "ATLAS_PANDABIGMON"."AUTH_GROUP" TO "ATLAS_PANDABIGMON_R";
  GRANT INSERT ON "ATLAS_PANDABIGMON"."AUTH_GROUP" TO "ATLAS_PANDABIGMON_R";
  GRANT UPDATE ON "ATLAS_PANDABIGMON"."AUTH_GROUP" TO "ATLAS_PANDABIGMON_R";

--------------------------------------------------------
--  DDL for Table AUTH_GROUP_PERMISSIONS
--------------------------------------------------------

  CREATE TABLE "ATLAS_PANDABIGMON"."AUTH_GROUP_PERMISSIONS" 
   (	"ID" NUMBER(11,0), 
	"GROUP_ID" NUMBER(11,0), 
	"PERMISSION_ID" NUMBER(11,0)
   );
  GRANT DELETE ON "ATLAS_PANDABIGMON"."AUTH_GROUP_PERMISSIONS" TO "ATLAS_PANDABIGMON_W";
  GRANT INSERT ON "ATLAS_PANDABIGMON"."AUTH_GROUP_PERMISSIONS" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."AUTH_GROUP_PERMISSIONS" TO "ATLAS_PANDABIGMON_W";
  GRANT UPDATE ON "ATLAS_PANDABIGMON"."AUTH_GROUP_PERMISSIONS" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."AUTH_GROUP_PERMISSIONS" TO "ATLAS_PANDABIGMON_R";
  GRANT DELETE ON "ATLAS_PANDABIGMON"."AUTH_GROUP_PERMISSIONS" TO "ATLAS_PANDABIGMON_R";
  GRANT INDEX ON "ATLAS_PANDABIGMON"."AUTH_GROUP_PERMISSIONS" TO "ATLAS_PANDABIGMON_R";
  GRANT INSERT ON "ATLAS_PANDABIGMON"."AUTH_GROUP_PERMISSIONS" TO "ATLAS_PANDABIGMON_R";
  GRANT UPDATE ON "ATLAS_PANDABIGMON"."AUTH_GROUP_PERMISSIONS" TO "ATLAS_PANDABIGMON_R";

--------------------------------------------------------
--  DDL for Table AUTH_USER
--------------------------------------------------------

  CREATE TABLE "ATLAS_PANDABIGMON"."AUTH_USER" 
   (	"ID" NUMBER(12,0), 
	"PASSWORD" VARCHAR2(128 BYTE), 
	"LAST_LOGIN" TIMESTAMP (3), 
	"IS_SUPERUSER" NUMBER(1,0), 
	"USERNAME" VARCHAR2(100 BYTE), 
	"FIRST_NAME" VARCHAR2(100 BYTE), 
	"LAST_NAME" VARCHAR2(100 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"IS_STAFF" NUMBER(1,0), 
	"IS_ACTIVE" NUMBER(1,0), 
	"DATE_JOINED" TIMESTAMP (3), 
	"IS_TESTER" NUMBER(1,0),
	"IS_EXPERT" NUMBER(1,0)
   );
  GRANT DELETE ON "ATLAS_PANDABIGMON"."AUTH_USER" TO "ATLAS_PANDABIGMON_W";
  GRANT INSERT ON "ATLAS_PANDABIGMON"."AUTH_USER" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."AUTH_USER" TO "ATLAS_PANDABIGMON_W";
  GRANT UPDATE ON "ATLAS_PANDABIGMON"."AUTH_USER" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."AUTH_USER" TO "ATLAS_PANDABIGMON_R";
  GRANT DELETE ON "ATLAS_PANDABIGMON"."AUTH_USER" TO "ATLAS_PANDABIGMON_R";
  GRANT INSERT ON "ATLAS_PANDABIGMON"."AUTH_USER" TO "ATLAS_PANDABIGMON_R";
  GRANT UPDATE ON "ATLAS_PANDABIGMON"."AUTH_USER" TO "ATLAS_PANDABIGMON_R";

--------------------------------------------------------
--  DDL for Table AUTH_USER_GROUPS
--------------------------------------------------------

  CREATE TABLE "ATLAS_PANDABIGMON"."AUTH_USER_GROUPS" 
   (	"ID" NUMBER(11,0), 
	"USER_ID" NUMBER(11,0), 
	"GROUP_ID" NUMBER(11,0)
   );
  GRANT DELETE ON "ATLAS_PANDABIGMON"."AUTH_USER_GROUPS" TO "ATLAS_PANDABIGMON_W";
  GRANT INSERT ON "ATLAS_PANDABIGMON"."AUTH_USER_GROUPS" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."AUTH_USER_GROUPS" TO "ATLAS_PANDABIGMON_W";
  GRANT UPDATE ON "ATLAS_PANDABIGMON"."AUTH_USER_GROUPS" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."AUTH_USER_GROUPS" TO "ATLAS_PANDABIGMON_R";
  GRANT DELETE ON "ATLAS_PANDABIGMON"."AUTH_USER_GROUPS" TO "ATLAS_PANDABIGMON_R";
  GRANT INDEX ON "ATLAS_PANDABIGMON"."AUTH_USER_GROUPS" TO "ATLAS_PANDABIGMON_R";
  GRANT INSERT ON "ATLAS_PANDABIGMON"."AUTH_USER_GROUPS" TO "ATLAS_PANDABIGMON_R";
  GRANT UPDATE ON "ATLAS_PANDABIGMON"."AUTH_USER_GROUPS" TO "ATLAS_PANDABIGMON_R";

--------------------------------------------------------
--  DDL for Table AUTH_USER_USER_PERMISSIONS
--------------------------------------------------------

  CREATE TABLE "ATLAS_PANDABIGMON"."AUTH_USER_USER_PERMISSIONS" 
   (	"ID" NUMBER(11,0), 
	"USER_ID" NUMBER(11,0), 
	"PERMISSION_ID" NUMBER(11,0)
   );
  GRANT DELETE ON "ATLAS_PANDABIGMON"."AUTH_USER_USER_PERMISSIONS" TO "ATLAS_PANDABIGMON_W";
  GRANT INSERT ON "ATLAS_PANDABIGMON"."AUTH_USER_USER_PERMISSIONS" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."AUTH_USER_USER_PERMISSIONS" TO "ATLAS_PANDABIGMON_W";
  GRANT UPDATE ON "ATLAS_PANDABIGMON"."AUTH_USER_USER_PERMISSIONS" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."AUTH_USER_USER_PERMISSIONS" TO "ATLAS_PANDABIGMON_R";
  GRANT DELETE ON "ATLAS_PANDABIGMON"."AUTH_USER_USER_PERMISSIONS" TO "ATLAS_PANDABIGMON_R";
  GRANT INDEX ON "ATLAS_PANDABIGMON"."AUTH_USER_USER_PERMISSIONS" TO "ATLAS_PANDABIGMON_R";
  GRANT INSERT ON "ATLAS_PANDABIGMON"."AUTH_USER_USER_PERMISSIONS" TO "ATLAS_PANDABIGMON_R";
  GRANT UPDATE ON "ATLAS_PANDABIGMON"."AUTH_USER_USER_PERMISSIONS" TO "ATLAS_PANDABIGMON_R";

--------------------------------------------------------
--  DDL for Table DJANGOCACHE
--------------------------------------------------------

  CREATE TABLE "ATLAS_PANDABIGMON"."DJANGOCACHE" 
   (	"CACHE_KEY" VARCHAR2(1000 BYTE), 
	"EXPIRES" TIMESTAMP (0), 
	"VALUE" CLOB
   );
  GRANT DELETE ON "ATLAS_PANDABIGMON"."DJANGOCACHE" TO "ATLAS_PANDABIGMON_W";
  GRANT INSERT ON "ATLAS_PANDABIGMON"."DJANGOCACHE" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."DJANGOCACHE" TO "ATLAS_PANDABIGMON_W";
  GRANT UPDATE ON "ATLAS_PANDABIGMON"."DJANGOCACHE" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."DJANGOCACHE" TO "ATLAS_PANDABIGMON_R";
  GRANT DELETE ON "ATLAS_PANDABIGMON"."DJANGOCACHE" TO "ATLAS_PANDABIGMON_R";
  GRANT INSERT ON "ATLAS_PANDABIGMON"."DJANGOCACHE" TO "ATLAS_PANDABIGMON_R";
  GRANT UPDATE ON "ATLAS_PANDABIGMON"."DJANGOCACHE" TO "ATLAS_PANDABIGMON_R";

--------------------------------------------------------
--  DDL for Table DJANGO_MIGRATIONS
--------------------------------------------------------

  CREATE TABLE "ATLAS_PANDABIGMON"."DJANGO_MIGRATIONS" 
   (	"ID" NUMBER(11,0), 
	"APP" NVARCHAR2(255), 
	"NAME" NVARCHAR2(255), 
	"APPLIED" TIMESTAMP (6)
   );
  GRANT DELETE ON "ATLAS_PANDABIGMON"."DJANGO_MIGRATIONS" TO "ATLAS_PANDABIGMON_W";
  GRANT INSERT ON "ATLAS_PANDABIGMON"."DJANGO_MIGRATIONS" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."DJANGO_MIGRATIONS" TO "ATLAS_PANDABIGMON_W";
  GRANT UPDATE ON "ATLAS_PANDABIGMON"."DJANGO_MIGRATIONS" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."DJANGO_MIGRATIONS" TO "ATLAS_PANDABIGMON_R";

--------------------------------------------------------
--  DDL for Table DJANGO_SESSION
--------------------------------------------------------

  CREATE TABLE "ATLAS_PANDABIGMON"."DJANGO_SESSION" 
   (	"SESSION_KEY" VARCHAR2(40 BYTE), 
	"SESSION_DATA" VARCHAR2(4000 BYTE), 
	"EXPIRE_DATE" TIMESTAMP (6), 
	"TMP_SESSION_DATA" CLOB
   ) ENABLE ROW MOVEMENT ;
  GRANT DELETE ON "ATLAS_PANDABIGMON"."DJANGO_SESSION" TO "ATLAS_PANDABIGMON_W";
  GRANT INSERT ON "ATLAS_PANDABIGMON"."DJANGO_SESSION" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."DJANGO_SESSION" TO "ATLAS_PANDABIGMON_W";
  GRANT UPDATE ON "ATLAS_PANDABIGMON"."DJANGO_SESSION" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."DJANGO_SESSION" TO "ATLAS_PANDABIGMON_R";
  GRANT INSERT ON "ATLAS_PANDABIGMON"."DJANGO_SESSION" TO "ATLAS_PANDABIGMON_R";
  GRANT UPDATE ON "ATLAS_PANDABIGMON"."DJANGO_SESSION" TO "ATLAS_PANDABIGMON_R";
  GRANT DELETE ON "ATLAS_PANDABIGMON"."DJANGO_SESSION" TO "ATLAS_PANDABIGMON_R";

--------------------------------------------------------
--  DDL for Table JOBSPAGE_CUMULATIVE_RESULT
--------------------------------------------------------

  CREATE TABLE "ATLAS_PANDABIGMON"."JOBSPAGE_CUMULATIVE_RESULT" 
   (	"REQUEST_TOKEN" NUMBER(15,0), 
	"ATTR" VARCHAR2(50 BYTE), 
	"ATTR_VALUE" VARCHAR2(500 BYTE), 
	"NUM_OCCUR" NUMBER(10,0), 
	"NUM_ITERATIONS" NUMBER(4,0), 
	"TOKEN_INSERT_TSTAMP" DATE DEFAULT SYSDATE, 
	 CONSTRAINT "JOBSPAGE_PART_AGGR_ALL_PK" PRIMARY KEY ("REQUEST_TOKEN", "ATTR", "ATTR_VALUE") ENABLE
   );

   COMMENT ON TABLE "ATLAS_PANDABIGMON"."JOBSPAGE_CUMULATIVE_RESULT"  IS 'Table for hosting cumulative result when processing the data with the ATLAS_PANDABIGMON.QUERY_JOBSPAGE_ARCH_PARTITION function.';
  GRANT UPDATE ON "ATLAS_PANDABIGMON"."JOBSPAGE_CUMULATIVE_RESULT" TO "ATLAS_PANDABIGMON_W";
  GRANT DELETE ON "ATLAS_PANDABIGMON"."JOBSPAGE_CUMULATIVE_RESULT" TO "ATLAS_PANDABIGMON_W";
  GRANT DELETE ON "ATLAS_PANDABIGMON"."JOBSPAGE_CUMULATIVE_RESULT" TO "ATLAS_PANDABIGMON_R";
  GRANT INSERT ON "ATLAS_PANDABIGMON"."JOBSPAGE_CUMULATIVE_RESULT" TO "ATLAS_PANDABIGMON_W";
  GRANT INSERT ON "ATLAS_PANDABIGMON"."JOBSPAGE_CUMULATIVE_RESULT" TO "ATLAS_PANDABIGMON_R";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."JOBSPAGE_CUMULATIVE_RESULT" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."JOBSPAGE_CUMULATIVE_RESULT" TO "ATLAS_PANDABIGMON_R";
  GRANT DELETE ON "ATLAS_PANDABIGMON"."JOBSPAGE_CUMULATIVE_RESULT" TO "ATLAS_DBA";
  GRANT UPDATE ON "ATLAS_PANDABIGMON"."JOBSPAGE_CUMULATIVE_RESULT" TO "ATLAS_DBA";
  GRANT UPDATE ON "ATLAS_PANDABIGMON"."JOBSPAGE_CUMULATIVE_RESULT" TO "ATLAS_PANDABIGMON_R";

--------------------------------------------------------
--  DDL for Table OBJECTS_COMPARISON
--------------------------------------------------------

  CREATE TABLE "ATLAS_PANDABIGMON"."OBJECTS_COMPARISON" 
   (	"ID" NUMBER, 
	"USERID" NUMBER, 
	"OBJECT" VARCHAR2(20 BYTE), 
	"COMPARISON_LIST" VARCHAR2(200 BYTE)
   );
  GRANT DELETE ON "ATLAS_PANDABIGMON"."OBJECTS_COMPARISON" TO "ATLAS_PANDABIGMON_W";
  GRANT DELETE ON "ATLAS_PANDABIGMON"."OBJECTS_COMPARISON" TO "ATLAS_PANDABIGMON_R";
  GRANT INSERT ON "ATLAS_PANDABIGMON"."OBJECTS_COMPARISON" TO "ATLAS_PANDABIGMON_R";
  GRANT INSERT ON "ATLAS_PANDABIGMON"."OBJECTS_COMPARISON" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."OBJECTS_COMPARISON" TO "ATLAS_PANDABIGMON_W";
  GRANT UPDATE ON "ATLAS_PANDABIGMON"."OBJECTS_COMPARISON" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."OBJECTS_COMPARISON" TO "ATLAS_PANDABIGMON_R";
  GRANT UPDATE ON "ATLAS_PANDABIGMON"."OBJECTS_COMPARISON" TO "ATLAS_PANDABIGMON_R";

--------------------------------------------------------
--  DDL for Table REQUEST_STATS
--------------------------------------------------------

  CREATE TABLE "ATLAS_PANDABIGMON"."REQUEST_STATS" 
   (	"ID" NUMBER(10,0), 
	"SERVER" VARCHAR2(100 BYTE), 
	"REMOTE" VARCHAR2(100 BYTE), 
	"QTIME" TIMESTAMP (6), 
	"QDURATION" TIMESTAMP (6), 
	"LOAD" VARCHAR2(40 BYTE), 
	"MEM" VARCHAR2(40 BYTE), 
	"DESCRIPTION" VARCHAR2(4000 BYTE), 
	"URL" VARCHAR2(2500 BYTE), 
	"DURATION" NUMBER(*,0), 
	"REFERRER" VARCHAR2(4000 BYTE), 
	"USERAGENT" VARCHAR2(300 BYTE)
   );

   COMMENT ON COLUMN "ATLAS_PANDABIGMON"."REQUEST_STATS"."SERVER" IS 'Host name of the server executing the query';
   COMMENT ON COLUMN "ATLAS_PANDABIGMON"."REQUEST_STATS"."REMOTE" IS 'IP address of the originating request';
   COMMENT ON COLUMN "ATLAS_PANDABIGMON"."REQUEST_STATS"."QTIME" IS 'Start time of the query in UTC';
   COMMENT ON COLUMN "ATLAS_PANDABIGMON"."REQUEST_STATS"."QDURATION" IS 'End time of the query in UTC';
   COMMENT ON COLUMN "ATLAS_PANDABIGMON"."REQUEST_STATS"."LOAD" IS 'CPU load on the PanDA monitor machine at the time of the query ';
   COMMENT ON COLUMN "ATLAS_PANDABIGMON"."REQUEST_STATS"."MEM" IS 'Memory usage at time of the query in MB';
   COMMENT ON COLUMN "ATLAS_PANDABIGMON"."REQUEST_STATS"."URL" IS 'URL of the query';
   COMMENT ON COLUMN "ATLAS_PANDABIGMON"."REQUEST_STATS"."REFERRER" IS 'Previous request';
   COMMENT ON COLUMN "ATLAS_PANDABIGMON"."REQUEST_STATS"."USERAGENT" IS 'User agent';
  GRANT SELECT ON "ATLAS_PANDABIGMON"."REQUEST_STATS" TO "ATLAS_PANDAANALYTICS_R";
  GRANT DELETE ON "ATLAS_PANDABIGMON"."REQUEST_STATS" TO "ATLAS_PANDABIGMON_W";
  GRANT INSERT ON "ATLAS_PANDABIGMON"."REQUEST_STATS" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."REQUEST_STATS" TO "ATLAS_PANDABIGMON_W";
  GRANT UPDATE ON "ATLAS_PANDABIGMON"."REQUEST_STATS" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."REQUEST_STATS" TO "ATLAS_PANDABIGMON_R";
  GRANT INSERT ON "ATLAS_PANDABIGMON"."REQUEST_STATS" TO "ATLAS_PANDABIGMON_R";
  GRANT UPDATE ON "ATLAS_PANDABIGMON"."REQUEST_STATS" TO "ATLAS_PANDABIGMON_R";
  GRANT DELETE ON "ATLAS_PANDABIGMON"."REQUEST_STATS" TO "ATLAS_PANDABIGMON_R";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."REQUEST_STATS" TO "ATLAS_PANDA_READER";

--------------------------------------------------------
--  DDL for Table RUCIO_ACCOUNTS
--------------------------------------------------------

  CREATE TABLE "ATLAS_PANDABIGMON"."RUCIO_ACCOUNTS" 
   (	"CERTIFICATEDN" VARCHAR2(250 BYTE), 
	"RUCIO_ACCOUNT" VARCHAR2(100 BYTE), 
	"CREATE_TIME" DATE DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP(0)), 
	"ID" NUMBER(*,0)
   );
  GRANT DELETE ON "ATLAS_PANDABIGMON"."RUCIO_ACCOUNTS" TO "ATLAS_PANDABIGMON_R";
  GRANT INSERT ON "ATLAS_PANDABIGMON"."RUCIO_ACCOUNTS" TO "ATLAS_PANDABIGMON_R";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."RUCIO_ACCOUNTS" TO "ATLAS_PANDABIGMON_R";
  GRANT UPDATE ON "ATLAS_PANDABIGMON"."RUCIO_ACCOUNTS" TO "ATLAS_PANDABIGMON_R";

--------------------------------------------------------
--  DDL for Table SOCIAL_AUTH_ASSOCIATION
--------------------------------------------------------

  CREATE TABLE "ATLAS_PANDABIGMON"."SOCIAL_AUTH_ASSOCIATION" 
   (	"ID" NUMBER(11,0), 
	"SERVER_URL" NVARCHAR2(255), 
	"HANDLE" NVARCHAR2(255), 
	"SECRET" NVARCHAR2(255), 
	"ISSUED" NUMBER(11,0), 
	"LIFETIME" NUMBER(11,0), 
	"ASSOC_TYPE" NVARCHAR2(64)
   );
  GRANT DELETE ON "ATLAS_PANDABIGMON"."SOCIAL_AUTH_ASSOCIATION" TO "ATLAS_PANDABIGMON_W";
  GRANT INSERT ON "ATLAS_PANDABIGMON"."SOCIAL_AUTH_ASSOCIATION" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."SOCIAL_AUTH_ASSOCIATION" TO "ATLAS_PANDABIGMON_W";
  GRANT UPDATE ON "ATLAS_PANDABIGMON"."SOCIAL_AUTH_ASSOCIATION" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."SOCIAL_AUTH_ASSOCIATION" TO "ATLAS_PANDABIGMON_R";
  GRANT DELETE ON "ATLAS_PANDABIGMON"."SOCIAL_AUTH_ASSOCIATION" TO "ATLAS_PANDABIGMON_R";
  GRANT INDEX ON "ATLAS_PANDABIGMON"."SOCIAL_AUTH_ASSOCIATION" TO "ATLAS_PANDABIGMON_R";
  GRANT INSERT ON "ATLAS_PANDABIGMON"."SOCIAL_AUTH_ASSOCIATION" TO "ATLAS_PANDABIGMON_R";
  GRANT UPDATE ON "ATLAS_PANDABIGMON"."SOCIAL_AUTH_ASSOCIATION" TO "ATLAS_PANDABIGMON_R";

--------------------------------------------------------
--  DDL for Table SOCIAL_AUTH_CODE
--------------------------------------------------------

  CREATE TABLE "ATLAS_PANDABIGMON"."SOCIAL_AUTH_CODE" 
   (	"ID" NUMBER(11,0), 
	"EMAIL" NVARCHAR2(254), 
	"CODE" NVARCHAR2(32), 
	"VERIFIED" NUMBER(1,0)
   );
  GRANT DELETE ON "ATLAS_PANDABIGMON"."SOCIAL_AUTH_CODE" TO "ATLAS_PANDABIGMON_W";
  GRANT INSERT ON "ATLAS_PANDABIGMON"."SOCIAL_AUTH_CODE" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."SOCIAL_AUTH_CODE" TO "ATLAS_PANDABIGMON_W";
  GRANT UPDATE ON "ATLAS_PANDABIGMON"."SOCIAL_AUTH_CODE" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."SOCIAL_AUTH_CODE" TO "ATLAS_PANDABIGMON_R";
  GRANT DELETE ON "ATLAS_PANDABIGMON"."SOCIAL_AUTH_CODE" TO "ATLAS_PANDABIGMON_R";
  GRANT INDEX ON "ATLAS_PANDABIGMON"."SOCIAL_AUTH_CODE" TO "ATLAS_PANDABIGMON_R";
  GRANT INSERT ON "ATLAS_PANDABIGMON"."SOCIAL_AUTH_CODE" TO "ATLAS_PANDABIGMON_R";
  GRANT UPDATE ON "ATLAS_PANDABIGMON"."SOCIAL_AUTH_CODE" TO "ATLAS_PANDABIGMON_R";

--------------------------------------------------------
--  DDL for Table SOCIAL_AUTH_NONCE
--------------------------------------------------------

  CREATE TABLE "ATLAS_PANDABIGMON"."SOCIAL_AUTH_NONCE" 
   (	"ID" NUMBER(11,0), 
	"SERVER_URL" NVARCHAR2(255), 
	"TIMESTAMP" NUMBER(11,0), 
	"SALT" NVARCHAR2(65)
   );
  GRANT DELETE ON "ATLAS_PANDABIGMON"."SOCIAL_AUTH_NONCE" TO "ATLAS_PANDABIGMON_W";
  GRANT INSERT ON "ATLAS_PANDABIGMON"."SOCIAL_AUTH_NONCE" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."SOCIAL_AUTH_NONCE" TO "ATLAS_PANDABIGMON_W";
  GRANT UPDATE ON "ATLAS_PANDABIGMON"."SOCIAL_AUTH_NONCE" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."SOCIAL_AUTH_NONCE" TO "ATLAS_PANDABIGMON_R";
  GRANT DELETE ON "ATLAS_PANDABIGMON"."SOCIAL_AUTH_NONCE" TO "ATLAS_PANDABIGMON_R";
  GRANT INSERT ON "ATLAS_PANDABIGMON"."SOCIAL_AUTH_NONCE" TO "ATLAS_PANDABIGMON_R";
  GRANT UPDATE ON "ATLAS_PANDABIGMON"."SOCIAL_AUTH_NONCE" TO "ATLAS_PANDABIGMON_R";

--------------------------------------------------------
--  DDL for Table SOCIAL_AUTH_PARTIAL
--------------------------------------------------------

  CREATE TABLE "ATLAS_PANDABIGMON"."SOCIAL_AUTH_PARTIAL" 
   (	"ID" NUMBER(11,0), 
	"TOKEN" NVARCHAR2(32), 
	"NEXT_STEP" NUMBER(11,0), 
	"BACKEND" NVARCHAR2(32), 
	"DATA" NCLOB
   );
  GRANT DELETE ON "ATLAS_PANDABIGMON"."SOCIAL_AUTH_PARTIAL" TO "ATLAS_PANDABIGMON_W";
  GRANT INSERT ON "ATLAS_PANDABIGMON"."SOCIAL_AUTH_PARTIAL" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."SOCIAL_AUTH_PARTIAL" TO "ATLAS_PANDABIGMON_W";
  GRANT UPDATE ON "ATLAS_PANDABIGMON"."SOCIAL_AUTH_PARTIAL" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."SOCIAL_AUTH_PARTIAL" TO "ATLAS_PANDABIGMON_R";
  GRANT INDEX ON "ATLAS_PANDABIGMON"."SOCIAL_AUTH_PARTIAL" TO "ATLAS_PANDABIGMON_R";
  GRANT INSERT ON "ATLAS_PANDABIGMON"."SOCIAL_AUTH_PARTIAL" TO "ATLAS_PANDABIGMON_R";
  GRANT UPDATE ON "ATLAS_PANDABIGMON"."SOCIAL_AUTH_PARTIAL" TO "ATLAS_PANDABIGMON_R";

--------------------------------------------------------
--  DDL for Table SOCIAL_AUTH_USERSOCIALAUTH
--------------------------------------------------------

  CREATE TABLE "ATLAS_PANDABIGMON"."SOCIAL_AUTH_USERSOCIALAUTH" 
   (	"ID" NUMBER(11,0), 
	"PROVIDER" NVARCHAR2(32), 
	"UID" NVARCHAR2(255), 
	"EXTRA_DATA" NCLOB DEFAULT NULL, 
	"USER_ID" NUMBER(11,0), 
	"CREATED" DATE DEFAULT sysdate, 
	"MODIFIED" DATE DEFAULT sysdate
   );
  GRANT DELETE ON "ATLAS_PANDABIGMON"."SOCIAL_AUTH_USERSOCIALAUTH" TO "ATLAS_PANDABIGMON_W";
  GRANT INSERT ON "ATLAS_PANDABIGMON"."SOCIAL_AUTH_USERSOCIALAUTH" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."SOCIAL_AUTH_USERSOCIALAUTH" TO "ATLAS_PANDABIGMON_W";
  GRANT UPDATE ON "ATLAS_PANDABIGMON"."SOCIAL_AUTH_USERSOCIALAUTH" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."SOCIAL_AUTH_USERSOCIALAUTH" TO "ATLAS_PANDABIGMON_R";
  GRANT DELETE ON "ATLAS_PANDABIGMON"."SOCIAL_AUTH_USERSOCIALAUTH" TO "ATLAS_PANDABIGMON_R";
  GRANT INDEX ON "ATLAS_PANDABIGMON"."SOCIAL_AUTH_USERSOCIALAUTH" TO "ATLAS_PANDABIGMON_R";
  GRANT INSERT ON "ATLAS_PANDABIGMON"."SOCIAL_AUTH_USERSOCIALAUTH" TO "ATLAS_PANDABIGMON_R";
  GRANT UPDATE ON "ATLAS_PANDABIGMON"."SOCIAL_AUTH_USERSOCIALAUTH" TO "ATLAS_PANDABIGMON_R";

--------------------------------------------------------
--  DDL for Table TMP_IDS1DEBUG
--------------------------------------------------------

  CREATE TABLE "ATLAS_PANDABIGMON"."TMP_IDS1DEBUG" 
   (	"ID" NUMBER(11,0), 
	"TRANSACTIONKEY" NUMBER(11,0), 
	"INS_TIME" DATE DEFAULT sysdate
   )
  PARTITION BY RANGE ("INS_TIME") INTERVAL (INTERVAL '1' HOUR) 
 (PARTITION "IDS_OLD"  VALUES LESS THAN (TO_DATE(' 2020-01-14 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'));
  GRANT DELETE ON "ATLAS_PANDABIGMON"."TMP_IDS1DEBUG" TO "ATLAS_PANDABIGMON_W";
  GRANT INSERT ON "ATLAS_PANDABIGMON"."TMP_IDS1DEBUG" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."TMP_IDS1DEBUG" TO "ATLAS_PANDABIGMON_W";
  GRANT UPDATE ON "ATLAS_PANDABIGMON"."TMP_IDS1DEBUG" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."TMP_IDS1DEBUG" TO "ATLAS_PANDABIGMON_R";
  GRANT DELETE ON "ATLAS_PANDABIGMON"."TMP_IDS1DEBUG" TO "ATLAS_PANDA";
  GRANT INSERT ON "ATLAS_PANDABIGMON"."TMP_IDS1DEBUG" TO "ATLAS_PANDA";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."TMP_IDS1DEBUG" TO "ATLAS_PANDA";
  GRANT UPDATE ON "ATLAS_PANDABIGMON"."TMP_IDS1DEBUG" TO "ATLAS_PANDA";
  GRANT INDEX ON "ATLAS_PANDABIGMON"."TMP_IDS1DEBUG" TO "ATLAS_PANDA";
  GRANT DELETE ON "ATLAS_PANDABIGMON"."TMP_IDS1DEBUG" TO "ATLAS_PANDABIGMON_R";
  GRANT INDEX ON "ATLAS_PANDABIGMON"."TMP_IDS1DEBUG" TO "ATLAS_PANDABIGMON_R";
  GRANT INSERT ON "ATLAS_PANDABIGMON"."TMP_IDS1DEBUG" TO "ATLAS_PANDABIGMON_R";
  GRANT UPDATE ON "ATLAS_PANDABIGMON"."TMP_IDS1DEBUG" TO "ATLAS_PANDABIGMON_R";
--------------------------------------------------------
--  DDL for Table USER_SETTINGS
--------------------------------------------------------

  CREATE TABLE "ATLAS_PANDABIGMON"."USER_SETTINGS" 
   (	"ID" NUMBER, 
	"USERID" NUMBER, 
	"PAGE" VARCHAR2(100 BYTE), 
	"PREFERENCES" VARCHAR2(4000 BYTE) DEFAULT '{}'
   );

   COMMENT ON COLUMN "ATLAS_PANDABIGMON"."USER_SETTINGS"."USERID" IS 'ID of user in AUTH_USER ';
   COMMENT ON COLUMN "ATLAS_PANDABIGMON"."USER_SETTINGS"."PAGE" IS 'Name of bigpandamon page';
   COMMENT ON COLUMN "ATLAS_PANDABIGMON"."USER_SETTINGS"."PREFERENCES" IS 'Settings for bigpandamon page ';
  GRANT INSERT ON "ATLAS_PANDABIGMON"."USER_SETTINGS" TO "ATLAS_PANDABIGMON_R";
  GRANT UPDATE ON "ATLAS_PANDABIGMON"."USER_SETTINGS" TO "ATLAS_PANDABIGMON_R";
  GRANT DELETE ON "ATLAS_PANDABIGMON"."USER_SETTINGS" TO "ATLAS_PANDABIGMON_W";
  GRANT INSERT ON "ATLAS_PANDABIGMON"."USER_SETTINGS" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."USER_SETTINGS" TO "ATLAS_PANDABIGMON_W";
  GRANT UPDATE ON "ATLAS_PANDABIGMON"."USER_SETTINGS" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."USER_SETTINGS" TO "ATLAS_PANDABIGMON_R";

--------------------------------------------------------
--  DDL for Table VISITS
--------------------------------------------------------

  CREATE TABLE "ATLAS_PANDABIGMON"."VISITS" 
   (	"VISITID" NUMBER, 
	"URL" VARCHAR2(4000 BYTE), 
	"TIME" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"SERVICE" NUMBER(*,0), 
	"USERID" NUMBER(*,0), 
	"REMOTE" VARCHAR2(100 BYTE)
   );

   COMMENT ON COLUMN "ATLAS_PANDABIGMON"."VISITS"."VISITID" IS 'Counter';
   COMMENT ON COLUMN "ATLAS_PANDABIGMON"."VISITS"."TIME" IS 'Time of visit';
   COMMENT ON COLUMN "ATLAS_PANDABIGMON"."VISITS"."SERVICE" IS '0 - bigpanda monitor';
   COMMENT ON COLUMN "ATLAS_PANDABIGMON"."VISITS"."USERID" IS 'Id in usertable of the authenticated user table';
  GRANT DELETE ON "ATLAS_PANDABIGMON"."VISITS" TO "ATLAS_PANDABIGMON_R";
  GRANT INSERT ON "ATLAS_PANDABIGMON"."VISITS" TO "ATLAS_PANDABIGMON_R";
  GRANT DELETE ON "ATLAS_PANDABIGMON"."VISITS" TO "ATLAS_PANDABIGMON_W";
  GRANT INSERT ON "ATLAS_PANDABIGMON"."VISITS" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."VISITS" TO "ATLAS_PANDABIGMON_W";
  GRANT UPDATE ON "ATLAS_PANDABIGMON"."VISITS" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."VISITS" TO "ATLAS_PANDABIGMON_R";
  GRANT UPDATE ON "ATLAS_PANDABIGMON"."VISITS" TO "ATLAS_PANDABIGMON_R";

--------------------------------------------------------
--  DDL for Index ALL_REQUESTS_URLVIEW_QTIME_IDX
--------------------------------------------------------

  CREATE INDEX "ATLAS_PANDABIGMON"."ALL_REQUESTS_URLVIEW_QTIME_IDX" ON "ATLAS_PANDABIGMON"."ALL_REQUESTS" ("URLVIEW", "QTIME");

--------------------------------------------------------
--  DDL for Index ALL_REQUESTS_DAILY_IDX
--------------------------------------------------------

  CREATE INDEX "ATLAS_PANDABIGMON"."ALL_REQUESTS_DAILY_IDX" ON "ATLAS_PANDABIGMON"."ALL_REQUESTS_DAILY" ("ID");

--------------------------------------------------------
--  DDL for Index SYS_C002462745
--------------------------------------------------------

  CREATE UNIQUE INDEX "ATLAS_PANDABIGMON"."SYS_C002462745" ON "ATLAS_PANDABIGMON"."AUTH_GROUP" ("ID");

--------------------------------------------------------
--  DDL for Index SYS_C002462746
--------------------------------------------------------

  CREATE UNIQUE INDEX "ATLAS_PANDABIGMON"."SYS_C002462746" ON "ATLAS_PANDABIGMON"."AUTH_GROUP" ("NAME");

--------------------------------------------------------
--  DDL for Index SYS_C002462750
--------------------------------------------------------

  CREATE UNIQUE INDEX "ATLAS_PANDABIGMON"."SYS_C002462750" ON "ATLAS_PANDABIGMON"."AUTH_GROUP_PERMISSIONS" ("ID");

--------------------------------------------------------
--  DDL for Index AUTH_GROU_GROUP_ID__0CD325B0_U
--------------------------------------------------------

  CREATE UNIQUE INDEX "ATLAS_PANDABIGMON"."AUTH_GROU_GROUP_ID__0CD325B0_U" ON "ATLAS_PANDABIGMON"."AUTH_GROUP_PERMISSIONS" ("GROUP_ID", "PERMISSION_ID");

--------------------------------------------------------
--  DDL for Index AUTH_GROUP_GROUP_ID_B120CBF9
--------------------------------------------------------

  CREATE INDEX "ATLAS_PANDABIGMON"."AUTH_GROUP_GROUP_ID_B120CBF9" ON "ATLAS_PANDABIGMON"."AUTH_GROUP_PERMISSIONS" ("GROUP_ID");

--------------------------------------------------------
--  DDL for Index AUTH_GROUP_PERMISSION_84C5C92E
--------------------------------------------------------

  CREATE INDEX "ATLAS_PANDABIGMON"."AUTH_GROUP_PERMISSION_84C5C92E" ON "ATLAS_PANDABIGMON"."AUTH_GROUP_PERMISSIONS" ("PERMISSION_ID");

--------------------------------------------------------
--  DDL for Index AUTH_USER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ATLAS_PANDABIGMON"."AUTH_USER_PK" ON "ATLAS_PANDABIGMON"."AUTH_USER" ("ID");

--------------------------------------------------------
--  DDL for Index SYS_C002462754
--------------------------------------------------------

  CREATE UNIQUE INDEX "ATLAS_PANDABIGMON"."SYS_C002462754" ON "ATLAS_PANDABIGMON"."AUTH_USER_GROUPS" ("ID");

--------------------------------------------------------
--  DDL for Index AUTH_USER_USER_ID_G_94350C0C_U
--------------------------------------------------------

  CREATE UNIQUE INDEX "ATLAS_PANDABIGMON"."AUTH_USER_USER_ID_G_94350C0C_U" ON "ATLAS_PANDABIGMON"."AUTH_USER_GROUPS" ("USER_ID", "GROUP_ID");

--------------------------------------------------------
--  DDL for Index AUTH_USER__USER_ID_6A12ED8B
--------------------------------------------------------

  CREATE INDEX "ATLAS_PANDABIGMON"."AUTH_USER__USER_ID_6A12ED8B" ON "ATLAS_PANDABIGMON"."AUTH_USER_GROUPS" ("USER_ID");

--------------------------------------------------------
--  DDL for Index AUTH_USER__GROUP_ID_97559544
--------------------------------------------------------

CREATE INDEX "ATLAS_PANDABIGMON"."AUTH_USER__GROUP_ID_97559544" ON "ATLAS_PANDABIGMON"."AUTH_USER_GROUPS" ("GROUP_ID");

--------------------------------------------------------
--  DDL for Index SYS_C002462758
--------------------------------------------------------

CREATE UNIQUE INDEX "ATLAS_PANDABIGMON"."SYS_C002462758" ON "ATLAS_PANDABIGMON"."AUTH_USER_USER_PERMISSIONS" ("ID");

--------------------------------------------------------
--  DDL for Index AUTH_USER_USER_ID_P_14A6B632_U
--------------------------------------------------------

CREATE UNIQUE INDEX "ATLAS_PANDABIGMON"."AUTH_USER_USER_ID_P_14A6B632_U" ON "ATLAS_PANDABIGMON"."AUTH_USER_USER_PERMISSIONS" ("USER_ID", "PERMISSION_ID");

--------------------------------------------------------
--  DDL for Index AUTH_USER__USER_ID_A95EAD1B
--------------------------------------------------------

CREATE INDEX "ATLAS_PANDABIGMON"."AUTH_USER__USER_ID_A95EAD1B" ON "ATLAS_PANDABIGMON"."AUTH_USER_USER_PERMISSIONS" ("USER_ID");

--------------------------------------------------------
--  DDL for Index AUTH_USER__PERMISSION_1FBB5F2C
--------------------------------------------------------

CREATE INDEX "ATLAS_PANDABIGMON"."AUTH_USER__PERMISSION_1FBB5F2C" ON "ATLAS_PANDABIGMON"."AUTH_USER_USER_PERMISSIONS" ("PERMISSION_ID");

--------------------------------------------------------
--  DDL for Index DJANGOCACHE_PK
--------------------------------------------------------

CREATE UNIQUE INDEX "ATLAS_PANDABIGMON"."DJANGOCACHE_PK" ON "ATLAS_PANDABIGMON"."DJANGOCACHE" ("CACHE_KEY");

--------------------------------------------------------
--  DDL for Index DJANGOCACHE_INDX_EXPIRES
--------------------------------------------------------

CREATE INDEX "ATLAS_PANDABIGMON"."DJANGOCACHE_INDX_EXPIRES" ON "ATLAS_PANDABIGMON"."DJANGOCACHE" ("EXPIRES");

--------------------------------------------------------
--  DDL for Index SYS_C002462705
--------------------------------------------------------

CREATE UNIQUE INDEX "ATLAS_PANDABIGMON"."SYS_C002462705" ON "ATLAS_PANDABIGMON"."DJANGO_MIGRATIONS" ("ID");

--------------------------------------------------------
--  DDL for Index DJANGO_SESSION_PK
--------------------------------------------------------

CREATE UNIQUE INDEX "ATLAS_PANDABIGMON"."DJANGO_SESSION_PK" ON "ATLAS_PANDABIGMON"."DJANGO_SESSION" ("SESSION_KEY");

--------------------------------------------------------
--  DDL for Index DJANGO_SESSION_INX_EXP_DATE
--------------------------------------------------------

CREATE INDEX "ATLAS_PANDABIGMON"."DJANGO_SESSION_INX_EXP_DATE" ON "ATLAS_PANDABIGMON"."DJANGO_SESSION" ("EXPIRE_DATE");

--------------------------------------------------------
--  DDL for Index JOBSPAGE_PART_AGGR_ALL_PK
--------------------------------------------------------

CREATE UNIQUE INDEX "ATLAS_PANDABIGMON"."JOBSPAGE_PART_AGGR_ALL_PK" ON "ATLAS_PANDABIGMON"."JOBSPAGE_CUMULATIVE_RESULT" ("REQUEST_TOKEN", "ATTR", "ATTR_VALUE");

--------------------------------------------------------
--  DDL for Index OBJECTS_COMPARISON_PK
--------------------------------------------------------

CREATE UNIQUE INDEX "ATLAS_PANDABIGMON"."OBJECTS_COMPARISON_PK" ON "ATLAS_PANDABIGMON"."OBJECTS_COMPARISON" ("ID");

--------------------------------------------------------
--  DDL for Index REQUEST_STATS_PK
--------------------------------------------------------

CREATE UNIQUE INDEX "ATLAS_PANDABIGMON"."REQUEST_STATS_PK" ON "ATLAS_PANDABIGMON"."REQUEST_STATS" ("ID");

--------------------------------------------------------
--  DDL for Index REQUEST_STATS_REMOTE_QTIME_IDX
--------------------------------------------------------

CREATE INDEX "ATLAS_PANDABIGMON"."REQUEST_STATS_REMOTE_QTIME_IDX" ON "ATLAS_PANDABIGMON"."REQUEST_STATS" ("REMOTE", "QTIME");

--------------------------------------------------------
--  DDL for Index RUCIO_ACCOUNTS_IDX
--------------------------------------------------------

CREATE INDEX "ATLAS_PANDABIGMON"."RUCIO_ACCOUNTS_IDX" ON "ATLAS_PANDABIGMON"."RUCIO_ACCOUNTS" ("CERTIFICATEDN");

--------------------------------------------------------
--  DDL for Index SYS_C002462721
--------------------------------------------------------

CREATE UNIQUE INDEX "ATLAS_PANDABIGMON"."SYS_C002462721" ON "ATLAS_PANDABIGMON"."SOCIAL_AUTH_ASSOCIATION" ("ID");

--------------------------------------------------------
--  DDL for Index SOCIAL_AU_SERVER_UR_078BEFA2_U
--------------------------------------------------------

CREATE UNIQUE INDEX "ATLAS_PANDABIGMON"."SOCIAL_AU_SERVER_UR_078BEFA2_U" ON "ATLAS_PANDABIGMON"."SOCIAL_AUTH_ASSOCIATION" ("SERVER_URL", "HANDLE");

--------------------------------------------------------
--  DDL for Index SYS_C002462725
--------------------------------------------------------

CREATE UNIQUE INDEX "ATLAS_PANDABIGMON"."SYS_C002462725" ON "ATLAS_PANDABIGMON"."SOCIAL_AUTH_CODE" ("ID");

--------------------------------------------------------
--  DDL for Index SOCIAL_AU_EMAIL_COD_801B2D02_U
--------------------------------------------------------

CREATE UNIQUE INDEX "ATLAS_PANDABIGMON"."SOCIAL_AU_EMAIL_COD_801B2D02_U" ON "ATLAS_PANDABIGMON"."SOCIAL_AUTH_CODE" ("EMAIL", "CODE");

--------------------------------------------------------
--  DDL for Index SOCIAL_AUTH_CODE_CODE_A2393167
--------------------------------------------------------

CREATE INDEX "ATLAS_PANDABIGMON"."SOCIAL_AUTH_CODE_CODE_A2393167" ON "ATLAS_PANDABIGMON"."SOCIAL_AUTH_CODE" ("CODE");

--------------------------------------------------------
--  DDL for Index SYS_C002462728
--------------------------------------------------------

CREATE UNIQUE INDEX "ATLAS_PANDABIGMON"."SYS_C002462728" ON "ATLAS_PANDABIGMON"."SOCIAL_AUTH_NONCE" ("ID");

--------------------------------------------------------
--  DDL for Index SOCIAL_AU_SERVER_UR_F6284463_U
--------------------------------------------------------

CREATE UNIQUE INDEX "ATLAS_PANDABIGMON"."SOCIAL_AU_SERVER_UR_F6284463_U" ON "ATLAS_PANDABIGMON"."SOCIAL_AUTH_NONCE" ("SERVER_URL", "TIMESTAMP", "SALT");

--------------------------------------------------------
--  DDL for Index SYS_C002462740
--------------------------------------------------------

CREATE UNIQUE INDEX "ATLAS_PANDABIGMON"."SYS_C002462740" ON "ATLAS_PANDABIGMON"."SOCIAL_AUTH_PARTIAL" ("ID");

--------------------------------------------------------
--  DDL for Index SOCIAL_AUT_TOKEN_3017FEA3
--------------------------------------------------------

CREATE INDEX "ATLAS_PANDABIGMON"."SOCIAL_AUT_TOKEN_3017FEA3" ON "ATLAS_PANDABIGMON"."SOCIAL_AUTH_PARTIAL" ("TOKEN");

--------------------------------------------------------
--  DDL for Index SYS_C002462731
--------------------------------------------------------

CREATE UNIQUE INDEX "ATLAS_PANDABIGMON"."SYS_C002462731" ON "ATLAS_PANDABIGMON"."SOCIAL_AUTH_USERSOCIALAUTH" ("ID");

--------------------------------------------------------
--  DDL for Index SOCIAL_AU_PROVIDER__E6B5E668_U
--------------------------------------------------------

CREATE UNIQUE INDEX "ATLAS_PANDABIGMON"."SOCIAL_AU_PROVIDER__E6B5E668_U" ON "ATLAS_PANDABIGMON"."SOCIAL_AUTH_USERSOCIALAUTH" ("PROVIDER", "UID");

--------------------------------------------------------
--  DDL for Index SOCIAL_AUT_USER_ID_17D28448
--------------------------------------------------------

CREATE INDEX "ATLAS_PANDABIGMON"."SOCIAL_AUT_USER_ID_17D28448" ON "ATLAS_PANDABIGMON"."SOCIAL_AUTH_USERSOCIALAUTH" ("USER_ID");

--------------------------------------------------------
--  DDL for Index TMP_IDS1DEBUG_IDX_TRANS
--------------------------------------------------------

CREATE INDEX "ATLAS_PANDABIGMON"."TMP_IDS1DEBUG_IDX_TRANS" ON "ATLAS_PANDABIGMON"."TMP_IDS1DEBUG" ("TRANSACTIONKEY", "ID");

--------------------------------------------------------
--  DDL for Index USER_SETTINGS_PK
--------------------------------------------------------

CREATE UNIQUE INDEX "ATLAS_PANDABIGMON"."USER_SETTINGS_PK" ON "ATLAS_PANDABIGMON"."USER_SETTINGS" ("ID");

--------------------------------------------------------
--  DDL for Index PK_VISIT
--------------------------------------------------------

CREATE UNIQUE INDEX "ATLAS_PANDABIGMON"."PK_VISIT" ON "ATLAS_PANDABIGMON"."VISITS" ("VISITID");

--------------------------------------------------------
--  DDL for Index USER_IDX
--------------------------------------------------------

CREATE INDEX "ATLAS_PANDABIGMON"."USER_IDX" ON "ATLAS_PANDABIGMON"."VISITS" ("USERID");

--------------------------------------------------------
--  DDL for Trigger ALL_REQUESTS_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ATLAS_PANDABIGMON"."ALL_REQUESTS_TRG" 
BEFORE INSERT ON ALL_REQUESTS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "ATLAS_PANDABIGMON"."ALL_REQUESTS_TRG" DISABLE;

--------------------------------------------------------
--  DDL for Trigger AUTH_GROUP_TR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ATLAS_PANDABIGMON"."AUTH_GROUP_TR" 
BEFORE INSERT ON "AUTH_GROUP"
FOR EACH ROW
 WHEN (new."ID" IS NULL) BEGIN
        SELECT "AUTH_GROUP_SQ".nextval
        INTO :new."ID" FROM dual;
    END;
/
ALTER TRIGGER "ATLAS_PANDABIGMON"."AUTH_GROUP_TR" ENABLE;

--------------------------------------------------------
--  DDL for Trigger AUTH_GROUP_PERMISSIONS_TR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ATLAS_PANDABIGMON"."AUTH_GROUP_PERMISSIONS_TR" 
BEFORE INSERT ON "AUTH_GROUP_PERMISSIONS"
FOR EACH ROW
 WHEN (new."ID" IS NULL) BEGIN
        SELECT "AUTH_GROUP_PERMISSIONS_SQ".nextval
        INTO :new."ID" FROM dual;
    END;
/
ALTER TRIGGER "ATLAS_PANDABIGMON"."AUTH_GROUP_PERMISSIONS_TR" ENABLE;

--------------------------------------------------------
--  DDL for Trigger AUTH_USER_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ATLAS_PANDABIGMON"."AUTH_USER_TRG" 
BEFORE INSERT ON AUTH_USER 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT AUTH_USER_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "ATLAS_PANDABIGMON"."AUTH_USER_TRG" ENABLE;

--------------------------------------------------------
--  DDL for Trigger AUTH_USER_TR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ATLAS_PANDABIGMON"."AUTH_USER_TR" 
BEFORE INSERT ON "AUTH_USER"
FOR EACH ROW
 WHEN (new."ID" IS NULL) BEGIN
        SELECT "AUTH_USER_SQ".nextval
        INTO :new."ID" FROM dual;
    END;
/
ALTER TRIGGER "ATLAS_PANDABIGMON"."AUTH_USER_TR" ENABLE;

--------------------------------------------------------
--  DDL for Trigger AUTH_USER_GROUPS_TR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ATLAS_PANDABIGMON"."AUTH_USER_GROUPS_TR" 
BEFORE INSERT ON "AUTH_USER_GROUPS"
FOR EACH ROW
 WHEN (new."ID" IS NULL) BEGIN
        SELECT "AUTH_USER_GROUPS_SQ".nextval
        INTO :new."ID" FROM dual;
    END;
/
ALTER TRIGGER "ATLAS_PANDABIGMON"."AUTH_USER_GROUPS_TR" ENABLE;

--------------------------------------------------------
--  DDL for Trigger AUTH_USER_USER_PERMISSI17F3
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ATLAS_PANDABIGMON"."AUTH_USER_USER_PERMISSI17F3" 
BEFORE INSERT ON "AUTH_USER_USER_PERMISSIONS"
FOR EACH ROW
 WHEN (new."ID" IS NULL) BEGIN
        SELECT "AUTH_USER_USER_PERMISSI7B1E".nextval
        INTO :new."ID" FROM dual;
    END;
/
ALTER TRIGGER "ATLAS_PANDABIGMON"."AUTH_USER_USER_PERMISSI17F3" ENABLE;

--------------------------------------------------------
--  DDL for Trigger DJANGO_MIGRATIONS_TR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ATLAS_PANDABIGMON"."DJANGO_MIGRATIONS_TR" 
BEFORE INSERT ON "DJANGO_MIGRATIONS"
FOR EACH ROW
BEGIN
  SELECT DJANGO_MIGRATIONS_SQ.NEXTVAL
  INTO   :NEW.ID
  FROM   dual;
END;
/
ALTER TRIGGER "ATLAS_PANDABIGMON"."DJANGO_MIGRATIONS_TR" ENABLE;

--------------------------------------------------------
--  DDL for Trigger OBJECTS_COMPARISON_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ATLAS_PANDABIGMON"."OBJECTS_COMPARISON_TRG" 
BEFORE INSERT ON OBJECTS_COMPARISON 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT OBJECTS_COMPARISON_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "ATLAS_PANDABIGMON"."OBJECTS_COMPARISON_TRG" ENABLE;

--------------------------------------------------------
--  DDL for Trigger REQUEST_STATS_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ATLAS_PANDABIGMON"."REQUEST_STATS_TRIGGER" 
BEFORE INSERT ON request_stats
FOR EACH ROW

BEGIN
  SELECT request_stats_seq.NEXTVAL
  INTO   :new.id
  FROM   dual;
END;
/
ALTER TRIGGER "ATLAS_PANDABIGMON"."REQUEST_STATS_TRIGGER" ENABLE;

--------------------------------------------------------
--  DDL for Trigger RUCIO_ACCOUNTS_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ATLAS_PANDABIGMON"."RUCIO_ACCOUNTS_TRIGGER" 
BEFORE INSERT ON RUCIO_ACCOUNTS
FOR EACH ROW

BEGIN
  SELECT RUCIO_ACCOUNTS_SEQ.NEXTVAL
  INTO   :new.id
  FROM   dual;
END;



/
ALTER TRIGGER "ATLAS_PANDABIGMON"."RUCIO_ACCOUNTS_TRIGGER" ENABLE;

--------------------------------------------------------
--  DDL for Trigger SOCIAL_AUTH_ASSOCIATION_TR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ATLAS_PANDABIGMON"."SOCIAL_AUTH_ASSOCIATION_TR" 
BEFORE INSERT ON "SOCIAL_AUTH_ASSOCIATION"
FOR EACH ROW
 WHEN (new."ID" IS NULL) BEGIN
        SELECT "SOCIAL_AUTH_ASSOCIATION_SQ".nextval
        INTO :new."ID" FROM dual;
    END;
/
ALTER TRIGGER "ATLAS_PANDABIGMON"."SOCIAL_AUTH_ASSOCIATION_TR" ENABLE;

--------------------------------------------------------
--  DDL for Trigger SOCIAL_AUTH_CODE_TR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ATLAS_PANDABIGMON"."SOCIAL_AUTH_CODE_TR" 
BEFORE INSERT ON "SOCIAL_AUTH_CODE"
FOR EACH ROW
 WHEN (new."ID" IS NULL) BEGIN
        SELECT "SOCIAL_AUTH_CODE_SQ".nextval
        INTO :new."ID" FROM dual;
    END;
/
ALTER TRIGGER "ATLAS_PANDABIGMON"."SOCIAL_AUTH_CODE_TR" ENABLE;

--------------------------------------------------------
--  DDL for Trigger SOCIAL_AUTH_NONCE_TR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ATLAS_PANDABIGMON"."SOCIAL_AUTH_NONCE_TR" 
BEFORE INSERT ON "SOCIAL_AUTH_NONCE"
FOR EACH ROW
 WHEN (new."ID" IS NULL) BEGIN
        SELECT "SOCIAL_AUTH_NONCE_SQ".nextval
        INTO :new."ID" FROM dual;
    END;
/
ALTER TRIGGER "ATLAS_PANDABIGMON"."SOCIAL_AUTH_NONCE_TR" ENABLE;

--------------------------------------------------------
--  DDL for Trigger SOCIAL_AUTH_PARTIAL_TR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ATLAS_PANDABIGMON"."SOCIAL_AUTH_PARTIAL_TR" 
BEFORE INSERT ON "SOCIAL_AUTH_PARTIAL"
FOR EACH ROW
 WHEN (new."ID" IS NULL) BEGIN
        SELECT "SOCIAL_AUTH_PARTIAL_SQ".nextval
        INTO :new."ID" FROM dual;
    END;
/
ALTER TRIGGER "ATLAS_PANDABIGMON"."SOCIAL_AUTH_PARTIAL_TR" ENABLE;

--------------------------------------------------------
--  DDL for Trigger SOCIAL_AUTH_USERSOCIALA1245
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ATLAS_PANDABIGMON"."SOCIAL_AUTH_USERSOCIALA1245" 
BEFORE INSERT ON "SOCIAL_AUTH_USERSOCIALAUTH"
FOR EACH ROW
 WHEN (new."ID" IS NULL) BEGIN
        SELECT "SOCIAL_AUTH_USERSOCIALA0419".nextval
        INTO :new."ID" FROM dual;
    END;
/
ALTER TRIGGER "ATLAS_PANDABIGMON"."SOCIAL_AUTH_USERSOCIALA1245" ENABLE;

--------------------------------------------------------
--  DDL for Trigger USER_SETTINGS_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ATLAS_PANDABIGMON"."USER_SETTINGS_TRG" 
BEFORE INSERT ON USER_SETTINGS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "ATLAS_PANDABIGMON"."USER_SETTINGS_TRG" ENABLE;

--------------------------------------------------------
--  DDL for Trigger USER_SETTINGS_TR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ATLAS_PANDABIGMON"."USER_SETTINGS_TR" 
BEFORE INSERT ON USER_SETTINGS 
FOR EACH ROW
 WHEN (new."ID" IS NULL) BEGIN
        SELECT "USER_SETTINGS_SQ".nextval
        INTO :new."ID" FROM dual;
    END;
/
ALTER TRIGGER "ATLAS_PANDABIGMON"."USER_SETTINGS_TR" ENABLE;

--------------------------------------------------------
--  DDL for Trigger VISITS_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ATLAS_PANDABIGMON"."VISITS_TRIGGER" 
BEFORE INSERT ON VISITS
FOR EACH ROW
BEGIN
  SELECT VISITS_SEQ.NEXTVAL
  INTO   :NEW.VISITID
  FROM   dual;
END;
/
ALTER TRIGGER "ATLAS_PANDABIGMON"."VISITS_TRIGGER" ENABLE;

--------------------------------------------------------
--  Constraints for Table AUTH_GROUP
--------------------------------------------------------

ALTER TABLE "ATLAS_PANDABIGMON"."AUTH_GROUP" MODIFY ("ID" NOT NULL);
ALTER TABLE "ATLAS_PANDABIGMON"."AUTH_GROUP" ADD PRIMARY KEY ("ID");
ALTER TABLE "ATLAS_PANDABIGMON"."AUTH_GROUP" ADD UNIQUE ("NAME");

--------------------------------------------------------
--  Constraints for Table AUTH_GROUP_PERMISSIONS
--------------------------------------------------------

ALTER TABLE "ATLAS_PANDABIGMON"."AUTH_GROUP_PERMISSIONS" MODIFY ("ID" NOT NULL);
ALTER TABLE "ATLAS_PANDABIGMON"."AUTH_GROUP_PERMISSIONS" MODIFY ("GROUP_ID" NOT NULL);
ALTER TABLE "ATLAS_PANDABIGMON"."AUTH_GROUP_PERMISSIONS" MODIFY ("PERMISSION_ID" NOT NULL);
ALTER TABLE "ATLAS_PANDABIGMON"."AUTH_GROUP_PERMISSIONS" ADD PRIMARY KEY ("ID");
ALTER TABLE "ATLAS_PANDABIGMON"."AUTH_GROUP_PERMISSIONS" ADD CONSTRAINT "AUTH_GROU_GROUP_ID__0CD325B0_U" UNIQUE ("GROUP_ID", "PERMISSION_ID");

--------------------------------------------------------
--  Constraints for Table AUTH_USER
--------------------------------------------------------

ALTER TABLE "ATLAS_PANDABIGMON"."AUTH_USER" MODIFY ("ID" NOT NULL);
ALTER TABLE "ATLAS_PANDABIGMON"."AUTH_USER" ADD CONSTRAINT "AUTH_USER_PK" PRIMARY KEY ("ID");

--------------------------------------------------------
--  Constraints for Table AUTH_USER_GROUPS
--------------------------------------------------------

ALTER TABLE "ATLAS_PANDABIGMON"."AUTH_USER_GROUPS" MODIFY ("ID" NOT NULL);
ALTER TABLE "ATLAS_PANDABIGMON"."AUTH_USER_GROUPS" MODIFY ("USER_ID" NOT NULL);
ALTER TABLE "ATLAS_PANDABIGMON"."AUTH_USER_GROUPS" MODIFY ("GROUP_ID" NOT NULL);
ALTER TABLE "ATLAS_PANDABIGMON"."AUTH_USER_GROUPS" ADD PRIMARY KEY ("ID");
ALTER TABLE "ATLAS_PANDABIGMON"."AUTH_USER_GROUPS" ADD CONSTRAINT "AUTH_USER_USER_ID_G_94350C0C_U" UNIQUE ("USER_ID", "GROUP_ID");

--------------------------------------------------------
--  Constraints for Table AUTH_USER_USER_PERMISSIONS
--------------------------------------------------------

ALTER TABLE "ATLAS_PANDABIGMON"."AUTH_USER_USER_PERMISSIONS" MODIFY ("ID" NOT NULL);
ALTER TABLE "ATLAS_PANDABIGMON"."AUTH_USER_USER_PERMISSIONS" MODIFY ("USER_ID" NOT NULL);
ALTER TABLE "ATLAS_PANDABIGMON"."AUTH_USER_USER_PERMISSIONS" MODIFY ("PERMISSION_ID" NOT NULL);
ALTER TABLE "ATLAS_PANDABIGMON"."AUTH_USER_USER_PERMISSIONS" ADD PRIMARY KEY ("ID");
ALTER TABLE "ATLAS_PANDABIGMON"."AUTH_USER_USER_PERMISSIONS" ADD CONSTRAINT "AUTH_USER_USER_ID_P_14A6B632_U" UNIQUE ("USER_ID", "PERMISSION_ID");

--------------------------------------------------------
--  Constraints for Table DJANGOCACHE
--------------------------------------------------------

ALTER TABLE "ATLAS_PANDABIGMON"."DJANGOCACHE" MODIFY ("VALUE" NOT NULL);
ALTER TABLE "ATLAS_PANDABIGMON"."DJANGOCACHE" MODIFY ("CACHE_KEY" CONSTRAINT "DJANGOCACHE_KEY_NN" NOT NULL);
ALTER TABLE "ATLAS_PANDABIGMON"."DJANGOCACHE" MODIFY ("EXPIRES" CONSTRAINT "DJANGOCACHE_EXPIRES_NN" NOT NULL);
ALTER TABLE "ATLAS_PANDABIGMON"."DJANGOCACHE" ADD CONSTRAINT "DJANGOCACHE_PK" PRIMARY KEY ("CACHE_KEY");

--------------------------------------------------------
--  Constraints for Table DJANGO_MIGRATIONS
--------------------------------------------------------

ALTER TABLE "ATLAS_PANDABIGMON"."DJANGO_MIGRATIONS" MODIFY ("ID" NOT NULL);
ALTER TABLE "ATLAS_PANDABIGMON"."DJANGO_MIGRATIONS" MODIFY ("APPLIED" NOT NULL);
ALTER TABLE "ATLAS_PANDABIGMON"."DJANGO_MIGRATIONS" ADD PRIMARY KEY ("ID");

--------------------------------------------------------
--  Constraints for Table DJANGO_SESSION
--------------------------------------------------------

ALTER TABLE "ATLAS_PANDABIGMON"."DJANGO_SESSION" MODIFY ("SESSION_KEY" CONSTRAINT "SESSION_KEY_NN" NOT NULL);
ALTER TABLE "ATLAS_PANDABIGMON"."DJANGO_SESSION" MODIFY ("SESSION_DATA" CONSTRAINT "SESSION_DATA_NN" NOT NULL);
ALTER TABLE "ATLAS_PANDABIGMON"."DJANGO_SESSION" MODIFY ("EXPIRE_DATE" CONSTRAINT "EXPIRE_DATE_NN" NOT NULL);
ALTER TABLE "ATLAS_PANDABIGMON"."DJANGO_SESSION" ADD CONSTRAINT "DJANGO_SESSION_PK" PRIMARY KEY ("SESSION_KEY");

--------------------------------------------------------
--  Constraints for Table JOBSPAGE_CUMULATIVE_RESULT
--------------------------------------------------------

ALTER TABLE "ATLAS_PANDABIGMON"."JOBSPAGE_CUMULATIVE_RESULT" ADD CONSTRAINT "JOBSPAGE_PART_AGGR_ALL_PK" PRIMARY KEY ("REQUEST_TOKEN", "ATTR", "ATTR_VALUE");
ALTER TABLE "ATLAS_PANDABIGMON"."JOBSPAGE_CUMULATIVE_RESULT" MODIFY ("REQUEST_TOKEN" CONSTRAINT "JOBSPAGE_AGGR_ALL_REQTOKEN_NN" NOT NULL);

--------------------------------------------------------
--  Constraints for Table OBJECTS_COMPARISON
--------------------------------------------------------

ALTER TABLE "ATLAS_PANDABIGMON"."OBJECTS_COMPARISON" MODIFY ("ID" NOT NULL);
ALTER TABLE "ATLAS_PANDABIGMON"."OBJECTS_COMPARISON" MODIFY ("USERID" NOT NULL);
ALTER TABLE "ATLAS_PANDABIGMON"."OBJECTS_COMPARISON" ADD CONSTRAINT "OBJECTS_COMPARISON_PK" PRIMARY KEY ("ID");

--------------------------------------------------------
--  Constraints for Table REQUEST_STATS
--------------------------------------------------------

ALTER TABLE "ATLAS_PANDABIGMON"."REQUEST_STATS" MODIFY ("DURATION" NOT NULL);
ALTER TABLE "ATLAS_PANDABIGMON"."REQUEST_STATS" MODIFY ("URL" NOT NULL);
ALTER TABLE "ATLAS_PANDABIGMON"."REQUEST_STATS" MODIFY ("ID" CONSTRAINT "ID_NN" NOT NULL);
ALTER TABLE "ATLAS_PANDABIGMON"."REQUEST_STATS" MODIFY ("SERVER" CONSTRAINT "SERVER_NN" NOT NULL);
ALTER TABLE "ATLAS_PANDABIGMON"."REQUEST_STATS" MODIFY ("REMOTE" CONSTRAINT "REMOTE_NN" NOT NULL);
ALTER TABLE "ATLAS_PANDABIGMON"."REQUEST_STATS" MODIFY ("QTIME" CONSTRAINT "QTIME_NN" NOT NULL);
ALTER TABLE "ATLAS_PANDABIGMON"."REQUEST_STATS" MODIFY ("QDURATION" CONSTRAINT "QDURATION_NN" NOT NULL);
ALTER TABLE "ATLAS_PANDABIGMON"."REQUEST_STATS" MODIFY ("LOAD" CONSTRAINT "LOAD_NN" NOT NULL);
ALTER TABLE "ATLAS_PANDABIGMON"."REQUEST_STATS" MODIFY ("MEM" CONSTRAINT "MEM_NN" NOT NULL);
ALTER TABLE "ATLAS_PANDABIGMON"."REQUEST_STATS" MODIFY ("DESCRIPTION" CONSTRAINT "DESCRIPTION_NN" NOT NULL);
ALTER TABLE "ATLAS_PANDABIGMON"."REQUEST_STATS" ADD CONSTRAINT "REQUEST_STATS_PK" PRIMARY KEY ("ID");

--------------------------------------------------------
--  Constraints for Table SOCIAL_AUTH_ASSOCIATION
--------------------------------------------------------

ALTER TABLE "ATLAS_PANDABIGMON"."SOCIAL_AUTH_ASSOCIATION" MODIFY ("ID" NOT NULL);
ALTER TABLE "ATLAS_PANDABIGMON"."SOCIAL_AUTH_ASSOCIATION" MODIFY ("ISSUED" NOT NULL);
ALTER TABLE "ATLAS_PANDABIGMON"."SOCIAL_AUTH_ASSOCIATION" MODIFY ("LIFETIME" NOT NULL);
ALTER TABLE "ATLAS_PANDABIGMON"."SOCIAL_AUTH_ASSOCIATION" ADD PRIMARY KEY ("ID");
ALTER TABLE "ATLAS_PANDABIGMON"."SOCIAL_AUTH_ASSOCIATION" ADD CONSTRAINT "SOCIAL_AU_SERVER_UR_078BEFA2_U" UNIQUE ("SERVER_URL", "HANDLE");

--------------------------------------------------------
--  Constraints for Table SOCIAL_AUTH_CODE
--------------------------------------------------------

ALTER TABLE "ATLAS_PANDABIGMON"."SOCIAL_AUTH_CODE" MODIFY ("ID" NOT NULL);
ALTER TABLE "ATLAS_PANDABIGMON"."SOCIAL_AUTH_CODE" MODIFY ("VERIFIED" NOT NULL);
ALTER TABLE "ATLAS_PANDABIGMON"."SOCIAL_AUTH_CODE" ADD CHECK ("VERIFIED" IN (0,1)) ENABLE;
ALTER TABLE "ATLAS_PANDABIGMON"."SOCIAL_AUTH_CODE" ADD PRIMARY KEY ("ID");
ALTER TABLE "ATLAS_PANDABIGMON"."SOCIAL_AUTH_CODE" ADD CONSTRAINT "SOCIAL_AU_EMAIL_COD_801B2D02_U" UNIQUE ("EMAIL", "CODE");

--------------------------------------------------------
--  Constraints for Table SOCIAL_AUTH_NONCE
--------------------------------------------------------

ALTER TABLE "ATLAS_PANDABIGMON"."SOCIAL_AUTH_NONCE" MODIFY ("TIMESTAMP" NOT NULL);
ALTER TABLE "ATLAS_PANDABIGMON"."SOCIAL_AUTH_NONCE" ADD PRIMARY KEY ("ID");
ALTER TABLE "ATLAS_PANDABIGMON"."SOCIAL_AUTH_NONCE" MODIFY ("ID" NOT NULL);
ALTER TABLE "ATLAS_PANDABIGMON"."SOCIAL_AUTH_NONCE" ADD CONSTRAINT "SOCIAL_AU_SERVER_UR_F6284463_U" UNIQUE ("SERVER_URL", "TIMESTAMP", "SALT");

--------------------------------------------------------
--  Constraints for Table SOCIAL_AUTH_PARTIAL
--------------------------------------------------------

ALTER TABLE "ATLAS_PANDABIGMON"."SOCIAL_AUTH_PARTIAL" MODIFY ("ID" NOT NULL);
ALTER TABLE "ATLAS_PANDABIGMON"."SOCIAL_AUTH_PARTIAL" MODIFY ("NEXT_STEP" NOT NULL);
ALTER TABLE "ATLAS_PANDABIGMON"."SOCIAL_AUTH_PARTIAL" ADD CHECK ("NEXT_STEP" >= 0) ENABLE;
ALTER TABLE "ATLAS_PANDABIGMON"."SOCIAL_AUTH_PARTIAL" ADD PRIMARY KEY ("ID");

--------------------------------------------------------
--  Constraints for Table SOCIAL_AUTH_USERSOCIALAUTH
--------------------------------------------------------

ALTER TABLE "ATLAS_PANDABIGMON"."SOCIAL_AUTH_USERSOCIALAUTH" MODIFY ("ID" NOT NULL);
ALTER TABLE "ATLAS_PANDABIGMON"."SOCIAL_AUTH_USERSOCIALAUTH" MODIFY ("USER_ID" NOT NULL);
ALTER TABLE "ATLAS_PANDABIGMON"."SOCIAL_AUTH_USERSOCIALAUTH" ADD PRIMARY KEY ("ID");
ALTER TABLE "ATLAS_PANDABIGMON"."SOCIAL_AUTH_USERSOCIALAUTH" ADD CONSTRAINT "SOCIAL_AU_PROVIDER__E6B5E668_U" UNIQUE ("PROVIDER", "UID");

--------------------------------------------------------
--  Constraints for Table USER_SETTINGS
--------------------------------------------------------

ALTER TABLE "ATLAS_PANDABIGMON"."USER_SETTINGS" MODIFY ("ID" NOT NULL);
ALTER TABLE "ATLAS_PANDABIGMON"."USER_SETTINGS" MODIFY ("USERID" NOT NULL);
ALTER TABLE "ATLAS_PANDABIGMON"."USER_SETTINGS" MODIFY ("PAGE" NOT NULL);
ALTER TABLE "ATLAS_PANDABIGMON"."USER_SETTINGS" MODIFY ("PREFERENCES" NOT NULL);
ALTER TABLE "ATLAS_PANDABIGMON"."USER_SETTINGS" ADD CONSTRAINT "USER_SETTINGS_PK" PRIMARY KEY ("ID");

--------------------------------------------------------
--  Constraints for Table VISITS
--------------------------------------------------------

ALTER TABLE "ATLAS_PANDABIGMON"."VISITS" ADD CONSTRAINT "PK_VISIT" PRIMARY KEY ("VISITID");

--------------------------------------------------------
--  Ref Constraints for Table AUTH_GROUP_PERMISSIONS
--------------------------------------------------------

ALTER TABLE "ATLAS_PANDABIGMON"."AUTH_GROUP_PERMISSIONS" ADD CONSTRAINT "AUTH_GROU_GROUP_ID_B120CBF9_F" FOREIGN KEY ("GROUP_ID")
  REFERENCES "ATLAS_PANDABIGMON"."AUTH_GROUP" ("ID") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "ATLAS_PANDABIGMON"."AUTH_GROUP_PERMISSIONS" ADD CONSTRAINT "AUTH_GROU_PERMISSIO_84C5C92E_F" FOREIGN KEY ("PERMISSION_ID")
  REFERENCES "ATLAS_PANDABIGMON"."AUTH_PERMISSION" ("ID") DEFERRABLE INITIALLY DEFERRED;

--------------------------------------------------------
--  Ref Constraints for Table AUTH_USER_GROUPS
--------------------------------------------------------

ALTER TABLE "ATLAS_PANDABIGMON"."AUTH_USER_GROUPS" ADD CONSTRAINT "AUTH_USER_USER_ID_6A12ED8B_F" FOREIGN KEY ("USER_ID")
  REFERENCES "ATLAS_PANDABIGMON"."AUTH_USER" ("ID") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "ATLAS_PANDABIGMON"."AUTH_USER_GROUPS" ADD CONSTRAINT "AUTH_USER_GROUP_ID_97559544_F" FOREIGN KEY ("GROUP_ID")
  REFERENCES "ATLAS_PANDABIGMON"."AUTH_GROUP" ("ID") DEFERRABLE INITIALLY DEFERRED;

--------------------------------------------------------
--  Ref Constraints for Table AUTH_USER_USER_PERMISSIONS
--------------------------------------------------------

ALTER TABLE "ATLAS_PANDABIGMON"."AUTH_USER_USER_PERMISSIONS" ADD CONSTRAINT "AUTH_USER_USER_ID_A95EAD1B_F" FOREIGN KEY ("USER_ID")
  REFERENCES "ATLAS_PANDABIGMON"."AUTH_USER" ("ID") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "ATLAS_PANDABIGMON"."AUTH_USER_USER_PERMISSIONS" ADD CONSTRAINT "AUTH_USER_PERMISSIO_1FBB5F2C_F" FOREIGN KEY ("PERMISSION_ID")
  REFERENCES "ATLAS_PANDABIGMON"."AUTH_PERMISSION" ("ID") DEFERRABLE INITIALLY DEFERRED;

--------------------------------------------------------
--  Ref Constraints for Table SOCIAL_AUTH_USERSOCIALAUTH
--------------------------------------------------------

ALTER TABLE "ATLAS_PANDABIGMON"."SOCIAL_AUTH_USERSOCIALAUTH" ADD CONSTRAINT "SOCIAL_AU_USER_ID_17D28448_F" FOREIGN KEY ("USER_ID")
  REFERENCES "ATLAS_PANDABIGMON"."AUTH_USER" ("ID") DEFERRABLE INITIALLY DEFERRED;
