--------------------------------------------------------
--  File created - Thursday-November-17-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for View COMBINED_WAIT_ACT_DEF_ARCH4
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "ATLAS_PANDABIGMON"."COMBINED_WAIT_ACT_DEF_ARCH4" ("PARTID", "DBMODTIME", "PANDAID", "JOBDEFINITIONID", "SCHEDULERID", "PILOTID", "CREATIONTIME", "CREATIONHOST", "MODIFICATIONTIME", "MODIFICATIONHOST", "ATLASRELEASE", "TRANSFORMATION", "HOMEPACKAGE", "PRODSERIESLABEL", "PRODSOURCELABEL", "PRODUSERID", "ASSIGNEDPRIORITY", "CURRENTPRIORITY", "ATTEMPTNR", "MAXATTEMPT", "JOBSTATUS", "JOBNAME", "MAXCPUCOUNT", "MAXCPUUNIT", "MAXDISKCOUNT", "MAXDISKUNIT", "IPCONNECTIVITY", "MINRAMCOUNT", "MINRAMUNIT", "STARTTIME", "ENDTIME", "CPUCONSUMPTIONTIME", "CPUCONSUMPTIONUNIT", "COMMANDTOPILOT", "TRANSEXITCODE", "PILOTERRORCODE", "PILOTERRORDIAG", "EXEERRORCODE", "EXEERRORDIAG", "SUPERRORCODE", "SUPERRORDIAG", "DDMERRORCODE", "BROKERAGEERRORCODE", "BROKERAGEERRORDIAG", "JOBDISPATCHERERRORCODE", "JOBDISPATCHERERRORDIAG", "TASKBUFFERERRORCODE", "TASKBUFFERERRORDIAG", "COMPUTINGSITE", "COMPUTINGELEMENT", "JOBPARAMETERS", "METADATA", "PRODDBLOCK", "DISPATCHDBLOCK", "DESTINATIONDBLOCK", "DESTINATIONSE", "NEVENTS", "GRID", "CLOUD", "CPUCONVERSION", "SOURCESITE", "DESTINATIONSITE", "TRANSFERTYPE", "TASKID", "CMTCONFIG", "STATECHANGETIME", "PRODDBUPDATETIME", "LOCKEDBY", "RELOCATIONFLAG", "JOBEXECUTIONID", "VO", "PILOTTIMING", "WORKINGGROUP", "PROCESSINGTYPE", "PRODUSERNAME", "NINPUTFILES", "COUNTRYGROUP", "BATCHID", "PARENTID", "SPECIALHANDLING", "JOBSETID", "CORECOUNT", "NINPUTDATAFILES", "INPUTFILETYPE", "INPUTFILEPROJECT", "INPUTFILEBYTES", "NOUTPUTDATAFILES", "OUTPUTFILEBYTES", "JOBMETRICS", "WORKQUEUE_ID", "JEDITASKID", "JOBSUBSTATUS", "ACTUALCORECOUNT", "REQID", "MAXRSS", "MAXVMEM", "MAXSWAP", "MAXPSS", "AVGRSS", "AVGVMEM", "AVGSWAP", "AVGPSS", "MAXWALLTIME", "NUCLEUS", "RESOURCE_TYPE", "ES", "TASKNAME", "TASKTYPE", "ISARCHIVE", "EVENTSERVICE", "USERNAME") AS 
  SELECT PARTID, DBMODTIME , t1."PANDAID",t1."JOBDEFINITIONID",t1."SCHEDULERID",t1."PILOTID",t1."CREATIONTIME",t1."CREATIONHOST",t1."MODIFICATIONTIME",t1."MODIFICATIONHOST",t1."ATLASRELEASE",t1."TRANSFORMATION",t1."HOMEPACKAGE",t1."PRODSERIESLABEL",t1."PRODSOURCELABEL",t1."PRODUSERID",t1."ASSIGNEDPRIORITY",t1."CURRENTPRIORITY",t1."ATTEMPTNR",t1."MAXATTEMPT",t1."JOBSTATUS",t1."JOBNAME",t1."MAXCPUCOUNT",t1."MAXCPUUNIT",t1."MAXDISKCOUNT",t1."MAXDISKUNIT",t1."IPCONNECTIVITY",t1."MINRAMCOUNT",t1."MINRAMUNIT",t1."STARTTIME",t1."ENDTIME",t1."CPUCONSUMPTIONTIME",t1."CPUCONSUMPTIONUNIT",t1."COMMANDTOPILOT",t1."TRANSEXITCODE",t1."PILOTERRORCODE",t1."PILOTERRORDIAG",t1."EXEERRORCODE",t1."EXEERRORDIAG",t1."SUPERRORCODE",t1."SUPERRORDIAG",t1."DDMERRORCODE",t1."BROKERAGEERRORCODE",t1."BROKERAGEERRORDIAG",t1."JOBDISPATCHERERRORCODE",t1."JOBDISPATCHERERRORDIAG",t1."TASKBUFFERERRORCODE",t1."TASKBUFFERERRORDIAG",t1."COMPUTINGSITE",t1."COMPUTINGELEMENT",t1."JOBPARAMETERS",t1."METADATA",t1."PRODDBLOCK",t1."DISPATCHDBLOCK",t1."DESTINATIONDBLOCK",t1."DESTINATIONSE",t1."NEVENTS",t1."GRID",t1."CLOUD",t1."CPUCONVERSION",t1."SOURCESITE",t1."DESTINATIONSITE",t1."TRANSFERTYPE",t1."TASKID",t1."CMTCONFIG",t1."STATECHANGETIME",t1."PRODDBUPDATETIME",t1."LOCKEDBY",t1."RELOCATIONFLAG",t1."JOBEXECUTIONID",t1."VO",t1."PILOTTIMING",t1."WORKINGGROUP",t1."PROCESSINGTYPE",t1."PRODUSERNAME",t1."NINPUTFILES",t1."COUNTRYGROUP",t1."BATCHID",t1."PARENTID",t1."SPECIALHANDLING",t1."JOBSETID",t1."CORECOUNT",t1."NINPUTDATAFILES",t1."INPUTFILETYPE",t1."INPUTFILEPROJECT",t1."INPUTFILEBYTES",t1."NOUTPUTDATAFILES",t1."OUTPUTFILEBYTES",t1."JOBMETRICS",t1."WORKQUEUE_ID",t1."JEDITASKID",t1."JOBSUBSTATUS",t1."ACTUALCORECOUNT",t1."REQID",t1."MAXRSS",t1."MAXVMEM",t1."MAXSWAP",t1."MAXPSS",t1."AVGRSS",t1."AVGVMEM",t1."AVGSWAP",t1."AVGPSS",t1."MAXWALLTIME", t1."NUCLEUS", t1."RESOURCE_TYPE", t1."ES", t2.TASKNAME, t2.TASKTYPE, t1.isarchive, t1.eventservice, t2.USERNAME FROM
(
SELECT 
CAST( ORA_HASH(PANDAID, 20) as NUMBER(9)) AS  PARTID,
ORA_ROWSCN AS DBMODTIME,
"PANDAID","JOBDEFINITIONID","SCHEDULERID","PILOTID","CREATIONTIME","CREATIONHOST","MODIFICATIONTIME","MODIFICATIONHOST","ATLASRELEASE","TRANSFORMATION","HOMEPACKAGE","PRODSERIESLABEL","PRODSOURCELABEL","PRODUSERID","ASSIGNEDPRIORITY","CURRENTPRIORITY","ATTEMPTNR","MAXATTEMPT","JOBSTATUS","JOBNAME","MAXCPUCOUNT","MAXCPUUNIT","MAXDISKCOUNT","MAXDISKUNIT","IPCONNECTIVITY","MINRAMCOUNT","MINRAMUNIT","STARTTIME","ENDTIME","CPUCONSUMPTIONTIME","CPUCONSUMPTIONUNIT","COMMANDTOPILOT","TRANSEXITCODE","PILOTERRORCODE","PILOTERRORDIAG","EXEERRORCODE","EXEERRORDIAG","SUPERRORCODE","SUPERRORDIAG","DDMERRORCODE","BROKERAGEERRORCODE","BROKERAGEERRORDIAG","JOBDISPATCHERERRORCODE","JOBDISPATCHERERRORDIAG","TASKBUFFERERRORCODE","TASKBUFFERERRORDIAG","COMPUTINGSITE","COMPUTINGELEMENT","JOBPARAMETERS","METADATA","PRODDBLOCK","DISPATCHDBLOCK","DESTINATIONDBLOCK","DESTINATIONSE","NEVENTS","GRID","CLOUD","CPUCONVERSION","SOURCESITE","DESTINATIONSITE","TRANSFERTYPE","TASKID","CMTCONFIG","STATECHANGETIME","PRODDBUPDATETIME","LOCKEDBY","RELOCATIONFLAG","JOBEXECUTIONID","VO","PILOTTIMING","WORKINGGROUP","PROCESSINGTYPE","PRODUSERNAME","NINPUTFILES","COUNTRYGROUP","BATCHID","PARENTID","SPECIALHANDLING","JOBSETID","CORECOUNT","NINPUTDATAFILES","INPUTFILETYPE","INPUTFILEPROJECT","INPUTFILEBYTES","NOUTPUTDATAFILES","OUTPUTFILEBYTES","JOBMETRICS","WORKQUEUE_ID","JEDITASKID","JOBSUBSTATUS","ACTUALCORECOUNT","REQID","MAXRSS","MAXVMEM","MAXSWAP","MAXPSS","AVGRSS","AVGVMEM","AVGSWAP","AVGPSS","MAXWALLTIME", "NUCLEUS",  "RESOURCE_TYPE",
CASE WHEN (eventservice in (1,2,4,5) and not specialhandling like '%sc:%') THEN eventservice 
     ELSE 0 END AS ES, 0 as isarchive, eventservice
FROM ATLAS_PANDA.JOBSDEFINED4 UNION ALL
SELECT 
CAST( ORA_HASH(PANDAID, 20) as NUMBER(9)) AS  PARTID,
ORA_ROWSCN AS DBMODTIME,
"PANDAID","JOBDEFINITIONID","SCHEDULERID","PILOTID","CREATIONTIME","CREATIONHOST","MODIFICATIONTIME","MODIFICATIONHOST","ATLASRELEASE","TRANSFORMATION","HOMEPACKAGE","PRODSERIESLABEL","PRODSOURCELABEL","PRODUSERID","ASSIGNEDPRIORITY","CURRENTPRIORITY","ATTEMPTNR","MAXATTEMPT","JOBSTATUS","JOBNAME","MAXCPUCOUNT","MAXCPUUNIT","MAXDISKCOUNT","MAXDISKUNIT","IPCONNECTIVITY","MINRAMCOUNT","MINRAMUNIT","STARTTIME","ENDTIME","CPUCONSUMPTIONTIME","CPUCONSUMPTIONUNIT","COMMANDTOPILOT","TRANSEXITCODE","PILOTERRORCODE","PILOTERRORDIAG","EXEERRORCODE","EXEERRORDIAG","SUPERRORCODE","SUPERRORDIAG","DDMERRORCODE","BROKERAGEERRORCODE","BROKERAGEERRORDIAG","JOBDISPATCHERERRORCODE","JOBDISPATCHERERRORDIAG","TASKBUFFERERRORCODE","TASKBUFFERERRORDIAG","COMPUTINGSITE","COMPUTINGELEMENT","JOBPARAMETERS","METADATA","PRODDBLOCK","DISPATCHDBLOCK","DESTINATIONDBLOCK","DESTINATIONSE","NEVENTS","GRID","CLOUD","CPUCONVERSION","SOURCESITE","DESTINATIONSITE","TRANSFERTYPE","TASKID","CMTCONFIG","STATECHANGETIME","PRODDBUPDATETIME","LOCKEDBY","RELOCATIONFLAG","JOBEXECUTIONID","VO","PILOTTIMING","WORKINGGROUP","PROCESSINGTYPE","PRODUSERNAME","NINPUTFILES","COUNTRYGROUP","BATCHID","PARENTID","SPECIALHANDLING","JOBSETID","CORECOUNT","NINPUTDATAFILES","INPUTFILETYPE","INPUTFILEPROJECT","INPUTFILEBYTES","NOUTPUTDATAFILES","OUTPUTFILEBYTES","JOBMETRICS","WORKQUEUE_ID","JEDITASKID","JOBSUBSTATUS","ACTUALCORECOUNT","REQID","MAXRSS","MAXVMEM","MAXSWAP","MAXPSS","AVGRSS","AVGVMEM","AVGSWAP","AVGPSS","MAXWALLTIME", "NUCLEUS",  "RESOURCE_TYPE",
CASE WHEN (eventservice in (1,2,4,5) and not specialhandling like '%sc:%') THEN eventservice 
     ELSE 0 END AS ES, 0 as isarchive, eventservice
     
FROM ATLAS_PANDA.JOBSWAITING4 UNION ALL
SELECT 
CAST( ORA_HASH(PANDAID, 20) as NUMBER(9)) AS  PARTID,
ORA_ROWSCN AS DBMODTIME,
"PANDAID","JOBDEFINITIONID","SCHEDULERID","PILOTID","CREATIONTIME","CREATIONHOST","MODIFICATIONTIME","MODIFICATIONHOST","ATLASRELEASE","TRANSFORMATION","HOMEPACKAGE","PRODSERIESLABEL","PRODSOURCELABEL","PRODUSERID","ASSIGNEDPRIORITY","CURRENTPRIORITY","ATTEMPTNR","MAXATTEMPT","JOBSTATUS","JOBNAME","MAXCPUCOUNT","MAXCPUUNIT","MAXDISKCOUNT","MAXDISKUNIT","IPCONNECTIVITY","MINRAMCOUNT","MINRAMUNIT","STARTTIME","ENDTIME","CPUCONSUMPTIONTIME","CPUCONSUMPTIONUNIT","COMMANDTOPILOT","TRANSEXITCODE","PILOTERRORCODE","PILOTERRORDIAG","EXEERRORCODE","EXEERRORDIAG","SUPERRORCODE","SUPERRORDIAG","DDMERRORCODE","BROKERAGEERRORCODE","BROKERAGEERRORDIAG","JOBDISPATCHERERRORCODE","JOBDISPATCHERERRORDIAG","TASKBUFFERERRORCODE","TASKBUFFERERRORDIAG","COMPUTINGSITE","COMPUTINGELEMENT","JOBPARAMETERS","METADATA","PRODDBLOCK","DISPATCHDBLOCK","DESTINATIONDBLOCK","DESTINATIONSE","NEVENTS","GRID","CLOUD","CPUCONVERSION","SOURCESITE","DESTINATIONSITE","TRANSFERTYPE","TASKID","CMTCONFIG","STATECHANGETIME","PRODDBUPDATETIME","LOCKEDBY","RELOCATIONFLAG","JOBEXECUTIONID","VO","PILOTTIMING","WORKINGGROUP","PROCESSINGTYPE","PRODUSERNAME","NINPUTFILES","COUNTRYGROUP","BATCHID","PARENTID","SPECIALHANDLING","JOBSETID","CORECOUNT","NINPUTDATAFILES","INPUTFILETYPE","INPUTFILEPROJECT","INPUTFILEBYTES","NOUTPUTDATAFILES","OUTPUTFILEBYTES","JOBMETRICS","WORKQUEUE_ID","JEDITASKID","JOBSUBSTATUS","ACTUALCORECOUNT","REQID","MAXRSS","MAXVMEM","MAXSWAP","MAXPSS","AVGRSS","AVGVMEM","AVGSWAP","AVGPSS","MAXWALLTIME", "NUCLEUS",  "RESOURCE_TYPE",
CASE WHEN (eventservice in (1,2,4,5) and not specialhandling like '%sc:%') THEN eventservice 
     ELSE 0 END AS ES, 0 as isarchive, eventservice
FROM ATLAS_PANDA.JOBSACTIVE4 UNION ALL
SELECT 
CAST( ORA_HASH(PANDAID, 20) as NUMBER(9)) AS  PARTID,
ORA_ROWSCN AS DBMODTIME,
"PANDAID","JOBDEFINITIONID","SCHEDULERID","PILOTID","CREATIONTIME","CREATIONHOST","MODIFICATIONTIME","MODIFICATIONHOST","ATLASRELEASE","TRANSFORMATION","HOMEPACKAGE","PRODSERIESLABEL","PRODSOURCELABEL","PRODUSERID","ASSIGNEDPRIORITY","CURRENTPRIORITY","ATTEMPTNR","MAXATTEMPT","JOBSTATUS","JOBNAME","MAXCPUCOUNT","MAXCPUUNIT","MAXDISKCOUNT","MAXDISKUNIT","IPCONNECTIVITY","MINRAMCOUNT","MINRAMUNIT","STARTTIME","ENDTIME","CPUCONSUMPTIONTIME","CPUCONSUMPTIONUNIT","COMMANDTOPILOT","TRANSEXITCODE","PILOTERRORCODE","PILOTERRORDIAG","EXEERRORCODE","EXEERRORDIAG","SUPERRORCODE","SUPERRORDIAG","DDMERRORCODE","BROKERAGEERRORCODE","BROKERAGEERRORDIAG","JOBDISPATCHERERRORCODE","JOBDISPATCHERERRORDIAG","TASKBUFFERERRORCODE","TASKBUFFERERRORDIAG","COMPUTINGSITE","COMPUTINGELEMENT","JOBPARAMETERS","METADATA","PRODDBLOCK","DISPATCHDBLOCK","DESTINATIONDBLOCK","DESTINATIONSE","NEVENTS","GRID","CLOUD","CPUCONVERSION","SOURCESITE","DESTINATIONSITE","TRANSFERTYPE","TASKID","CMTCONFIG","STATECHANGETIME","PRODDBUPDATETIME","LOCKEDBY","RELOCATIONFLAG","JOBEXECUTIONID","VO","PILOTTIMING","WORKINGGROUP","PROCESSINGTYPE","PRODUSERNAME","NINPUTFILES","COUNTRYGROUP","BATCHID","PARENTID","SPECIALHANDLING","JOBSETID","CORECOUNT","NINPUTDATAFILES","INPUTFILETYPE","INPUTFILEPROJECT","INPUTFILEBYTES","NOUTPUTDATAFILES","OUTPUTFILEBYTES","JOBMETRICS","WORKQUEUE_ID","JEDITASKID","JOBSUBSTATUS","ACTUALCORECOUNT","REQID","MAXRSS","MAXVMEM","MAXSWAP","MAXPSS","AVGRSS","AVGVMEM","AVGSWAP","AVGPSS","MAXWALLTIME", "NUCLEUS",  "RESOURCE_TYPE",
CASE WHEN (eventservice in (1,2,4,5) and not specialhandling like '%sc:%') THEN eventservice 
     ELSE 0 END AS ES, 1 as isarchive, eventservice
FROM ATLAS_PANDA.Jobsarchived4
)t1 LEFT JOIN ATLAS_PANDA.JEDI_TASKS t2 ON t1.JEDITASKID=t2.JEDITASKID WITH READ ONLY
;
  GRANT DELETE ON "ATLAS_PANDABIGMON"."COMBINED_WAIT_ACT_DEF_ARCH4" TO "ATLAS_PANDABIGMON_W";
  GRANT INSERT ON "ATLAS_PANDABIGMON"."COMBINED_WAIT_ACT_DEF_ARCH4" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."COMBINED_WAIT_ACT_DEF_ARCH4" TO "ATLAS_PANDABIGMON_R";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."COMBINED_WAIT_ACT_DEF_ARCH4" TO "ATLAS_PANDABIGMON_W";
  GRANT UPDATE ON "ATLAS_PANDABIGMON"."COMBINED_WAIT_ACT_DEF_ARCH4" TO "ATLAS_PANDABIGMON_W";
--------------------------------------------------------
--  DDL for View GETEVENTSFORTASK
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "ATLAS_PANDABIGMON"."GETEVENTSFORTASK" ("JEDITASKID", "TOTEVREM", "TOTEV", "MODIFICATIONTIME") AS 
  SELECT JEDITASKID, 
ROUND(SUM(
CASE WHEN NFILESUSED > 0 THEN (NFILES-NFILESFINISHED)/NFILES*NEVENTS
     ELSE 0
END
)) as TOTEVREM, SUM(NEVENTS) as TOTEV, MAX(MODIFICATIONTIME) as MODIFICATIONTIME FROM ATLAS_PANDA.JEDI_DATASETS WHERE (TYPE IN ('input','pseudo_input')) AND MASTERID IS NULL GROUP BY JEDITASKID WITH READ ONLY
;
  GRANT SELECT ON "ATLAS_PANDABIGMON"."GETEVENTSFORTASK" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."GETEVENTSFORTASK" TO "ATLAS_PANDABIGMON_R";
--------------------------------------------------------
--  DDL for View GETRWWITHPRIOJEDI3DAYS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "ATLAS_PANDABIGMON"."GETRWWITHPRIOJEDI3DAYS" ("JEDITASKID", "TASKNAME", "DATASETID", "MODIFICATIONTIME", "CLOUD", "CORECOUNT", "PROCESSINGTYPE", "RAMCOUNT", "RAMUNIT", "NREM", "PRODSOURCELABEL", "WALLTIME", "WORKINGGROUP", "FSIZE", "STARTEVENT", "ENDEVENT", "NEVENTS", "USERNAME") AS 
  SELECT t4.jediTaskID, t4.taskname, t4.datasetID, t4.modificationTime, t4.cloud, t4.corecount, t4.processingtype,
t4.ramcount, t4.ramunit, t4.nRem, t4.prodsourcelabel, t4.walltime, t4.workinggroup, t5.fsize, t5.startEvent, 
t5.endEvent, t5.nEvents, t4.username
FROM (
SELECT tabT.jediTaskID, tabT.MODIFICATIONTIME, tabT.cloud, tabT.CORECOUNT, tabT.processingtype,
tabT.ramcount, tabT.ramunit, tabT.PRODSOURCELABEL, tabT.taskname, tabT.WORKINGGROUP,
tabD.datasetID, nFiles-nFilesFinished-nFilesFailed as nRem, walltime, tabT.username
FROM ATLAS_PANDA.JEDI_Tasks tabT, ATLAS_PANDA.JEDI_Datasets tabD,
ATLAS_PANDA.JEDI_AUX_Status_MinTaskID tabA
WHERE (tabT.status=tabA.status AND tabT.jediTaskID>=tabA.min_jediTaskID
AND tabT.jediTaskID=tabD.jediTaskID AND masterID IS NULL
AND (nFiles-nFilesFinished-nFilesFailed)>0 AND (tabT.MODIFICATIONTIME >
sysdate-3) AND tabD.type IN ('input','pseudo_input') AND
tabT.status IN ('ready','scouting', 'running', 'pending') AND tabT.cloud
IS NOT NULL
))t4
LEFT JOIN
(
SELECT fsize, startEvent, endEvent, nEvents, DATASETID, jediTaskID,
ROW_NUMBER() OVER 
  (PARTITION BY DATASETID, jediTaskID ORDER BY FSIZE DESC) as RANK FROM
ATLAS_PANDA.JEDI_Dataset_Contents tabC
) t5
ON t4.jediTaskID=t5.jediTaskID AND t4.datasetID=t5.DATASETID AND t5.RANK
= 1 WITH READ ONLY
;
  GRANT SELECT ON "ATLAS_PANDABIGMON"."GETRWWITHPRIOJEDI3DAYS" TO "ATLAS_PANDABIGMON_R";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."GETRWWITHPRIOJEDI3DAYS" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."GETRWWITHPRIOJEDI3DAYS" TO "ATLAS_PANDAMON_READER";
  GRANT DELETE ON "ATLAS_PANDABIGMON"."GETRWWITHPRIOJEDI3DAYS" TO "ATLAS_PANDABIGMON_W";
  GRANT INSERT ON "ATLAS_PANDABIGMON"."GETRWWITHPRIOJEDI3DAYS" TO "ATLAS_PANDABIGMON_W";
  GRANT UPDATE ON "ATLAS_PANDABIGMON"."GETRWWITHPRIOJEDI3DAYS" TO "ATLAS_PANDABIGMON_W";
--------------------------------------------------------
--  DDL for View JEDI_TASKS_ORDERED
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "ATLAS_PANDABIGMON"."JEDI_TASKS_ORDERED" ("JEDITASKID", "TASKNAME", "STATUS", "USERNAME", "CREATIONDATE", "MODIFICATIONTIME", "REQID", "OLDSTATUS", "CLOUD", "SITE", "STARTTIME", "ENDTIME", "FROZENTIME", "PRODSOURCELABEL", "WORKINGGROUP", "VO", "CORECOUNT", "TASKTYPE", "PROCESSINGTYPE", "TASKPRIORITY", "CURRENTPRIORITY", "ARCHITECTURE", "TRANSUSES", "TRANSHOME", "TRANSPATH", "LOCKEDBY", "LOCKEDTIME", "TERMCONDITION", "SPLITRULE", "WALLTIME", "WALLTIMEUNIT", "OUTDISKCOUNT", "OUTDISKUNIT", "WORKDISKCOUNT", "WORKDISKUNIT", "RAMCOUNT", "RAMUNIT", "IOINTENSITY", "IOINTENSITYUNIT", "WORKQUEUE_ID", "PROGRESS", "FAILURERATE", "ERRORDIALOG", "COUNTRYGROUP", "PARENT_TID", "EVENTSERVICE", "TICKETID", "TICKETSYSTEMTYPE", "STATECHANGETIME", "SUPERSTATUS", "CAMPAIGN", "MERGERAMCOUNT", "MERGERAMUNIT", "MERGEWALLTIME", "MERGEWALLTIMEUNIT", "THROTTLEDTIME", "NUMTHROTTLED", "MERGECORECOUNT", "GOAL", "ASSESSMENTTIME", "CPUTIME", "CPUTIMEUNIT", "CPUEFFICIENCY", "BASEWALLTIME", "AMIFLAG_OLD", "AMIFLAG", "NUCLEUS", "BASERAMCOUNT", "TTCREQUESTED", "TTCPREDICTED", "TTCPREDICTIONDATE", "RESCUETIME", "REQUESTTYPE", "GSHARE", "RESOURCE_TYPE", "USEJUMBO", "DISKIO", "DISKIOUNIT", "CONTAINER_NAME", "ATTEMPTNR") AS 
  SELECT "JEDITASKID","TASKNAME","STATUS","USERNAME","CREATIONDATE",
"MODIFICATIONTIME","REQID","OLDSTATUS","CLOUD","SITE","STARTTIME","ENDTIME",
"FROZENTIME","PRODSOURCELABEL","WORKINGGROUP","VO","CORECOUNT","TASKTYPE",
"PROCESSINGTYPE","TASKPRIORITY","CURRENTPRIORITY","ARCHITECTURE","TRANSUSES",
"TRANSHOME","TRANSPATH","LOCKEDBY","LOCKEDTIME","TERMCONDITION","SPLITRULE"
,"WALLTIME","WALLTIMEUNIT","OUTDISKCOUNT","OUTDISKUNIT","WORKDISKCOUNT",
"WORKDISKUNIT","RAMCOUNT","RAMUNIT","IOINTENSITY","IOINTENSITYUNIT","WORKQUEUE_ID",
"PROGRESS","FAILURERATE","ERRORDIALOG","COUNTRYGROUP","PARENT_TID","EVENTSERVICE",
"TICKETID","TICKETSYSTEMTYPE","STATECHANGETIME","SUPERSTATUS","CAMPAIGN",
"MERGERAMCOUNT","MERGERAMUNIT","MERGEWALLTIME","MERGEWALLTIMEUNIT",
"THROTTLEDTIME","NUMTHROTTLED","MERGECORECOUNT","GOAL","ASSESSMENTTIME",
"CPUTIME","CPUTIMEUNIT","CPUEFFICIENCY","BASEWALLTIME","AMIFLAG_OLD","AMIFLAG",
"NUCLEUS","BASERAMCOUNT","TTCREQUESTED","TTCPREDICTED","TTCPREDICTIONDATE",
"RESCUETIME","REQUESTTYPE","GSHARE","RESOURCE_TYPE", "USEJUMBO", "DISKIO", 
"DISKIOUNIT","CONTAINER_NAME","ATTEMPTNR"
FROM ATLAS_PANDA.JEDI_TASKS 
ORDER BY JEDITASKID DESC
;
  GRANT SELECT ON "ATLAS_PANDABIGMON"."JEDI_TASKS_ORDERED" TO "ATLAS_PANDABIGMON_W";
  GRANT SELECT ON "ATLAS_PANDABIGMON"."JEDI_TASKS_ORDERED" TO "ATLAS_PANDABIGMON_R";
