GRANT SELECT on ATLAS_DEFT.PRODSYS2_TASK_ID_SEQ to ATLAS_PANDA:
GRANT SELECT,INSERT,UPDATE,DELETE on ATLAS_DEFT.PRODSYS_COMM to ATLAS_PANDA:
GRANT SELECT,INSERT,UPDATE,DELETE on ATLAS_DEFT.T_TASK to ATLAS_PANDA:

GRANT SELECT on ATLAS_DEFT.PRODSYS2_TASK_ID_SEQ to ATLAS_PANDA_WRITER:
GRANT SELECT,INSERT,UPDATE,DELETE on ATLAS_DEFT.PRODSYS_COMM to ATLAS_PANDA_WRITER:
GRANT SELECT,INSERT,UPDATE,DELETE on ATLAS_DEFT.T_TASK to ATLAS_PANDA_WRITER:

GRANT SELECT on ATLAS_DEFT.PRODSYS_COMM to ATLAS_PANDA_READER:
GRANT SELECT on ATLAS_DEFT.T_TASK to ATLAS_PANDA_READER:

-- Grants for async processing tables
GRANT SELECT ON ATLAS_PANDA.MACHINE_HEARTBEAT TO ATLAS_PANDA_READER;
GRANT SELECT ON ATLAS_PANDA.ASYNC_REQUESTS    TO ATLAS_PANDA_READER;
GRANT SELECT ON ATLAS_PANDA.ASYNC_RESULTS     TO ATLAS_PANDA_READER;

GRANT SELECT, INSERT, UPDATE, DELETE ON ATLAS_PANDA.MACHINE_HEARTBEAT TO ATLAS_PANDA_WRITER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ATLAS_PANDA.ASYNC_REQUESTS    TO ATLAS_PANDA_WRITER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ATLAS_PANDA.ASYNC_RESULTS     TO ATLAS_PANDA_WRITER;