GRANT SELECT on ATLAS_DEFT.PRODSYS2_TASK_ID_SEQ to ATLAS_PANDA:
GRANT SELECT,INSERT,UPDATE,DELETE on ATLAS_DEFT.PRODSYS_COMM to ATLAS_PANDA:
GRANT SELECT,INSERT,UPDATE,DELETE on ATLAS_DEFT.T_TASK to ATLAS_PANDA:

GRANT SELECT on ATLAS_DEFT.PRODSYS2_TASK_ID_SEQ to ATLAS_PANDA_WRITER:
GRANT SELECT,INSERT,UPDATE,DELETE on ATLAS_DEFT.PRODSYS_COMM to ATLAS_PANDA_WRITER:
GRANT SELECT,INSERT,UPDATE,DELETE on ATLAS_DEFT.T_TASK to ATLAS_PANDA_WRITER:

GRANT SELECT on ATLAS_DEFT.PRODSYS_COMM to ATLAS_PANDA_READER:
GRANT SELECT on ATLAS_DEFT.T_TASK to ATLAS_PANDA_READER: